# ==================================================================================================
# === Build duckling library =======================================================================

FROM docker.io/haskell:8 AS builder

RUN apt-get update -qq \
  && apt-get install -qq -y --fix-missing --no-install-recommends \
     libpcre3 libpcre3-dev build-essential pkg-config \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir /log/
WORKDIR /duckling/

ADD . .

ENV LANG=C.UTF-8
RUN stack setup

# NOTE:`stack build` will use as many cores as are available to build
# in parallel. However, this can cause OOM issues as the linking step
# in GHC can be expensive. If the build fails, try specifying the
# '-j1' flag to force the build to run sequentially.
RUN stack install --test --no-run-tests

# Run tests. If tests are not built in above step, the main library would be rebuilt here as well.
RUN stack test --system-ghc

# ==================================================================================================
# === Copy prebuilt files to new image to greatly reduce the image size ============================

FROM docker.io/debian:buster AS base

ENV LANG C.UTF-8

RUN apt-get update -qq \
  && apt-get install -qq -y --no-install-recommends \
     libpcre3 libgmp10 \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY --from=builder /root/.local/bin/duckling-example-exe /usr/local/bin/

# ==================================================================================================
# === Run a fast server test =======================================================================

FROM base

# Additional dependencies are required
RUN apt-get update -qq \
  && apt-get install -qq -y --no-install-recommends \
     curl \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Change default shell to enable below string comparison
SHELL ["/bin/bash", "-c"]

# Run simple test to check if requests are answered
RUN duckling-example-exe -p 8008 --no-access-log --no-error-log & \
  sleep 2 && \
  response=$(curl -XPOST http://0.0.0.0:8008/parse --data 'locale=en_GB&text=42€') && \
  label='{"value":42,"type":"value","unit":"EUR"}' && \
  if [[ "$response" == *"$label"* ]] ; then echo "ok" ; exit 0 ; else echo "error" ; exit -1 ; fi;

# ==================================================================================================
# === Now finish the image =========================================================================

FROM base

# Use port 8008 instead of default port, because port 8000 is already in use by portainer
EXPOSE 8008

CMD ["duckling-example-exe", "-p", "8008", "--no-access-log", "--no-error-log"]
