-- Copyright (c) 2016-present, Facebook, Inc.
-- All rights reserved.
--
-- This source code is licensed under the BSD-style license found in the
-- LICENSE file in the root directory of this source tree. An additional grant
-- of patent rights can be found in the PATENTS file in the same directory.

-----------------------------------------------------------------
-- Auto-generated by regenClassifiers
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
--  @generated
-----------------------------------------------------------------
{-# LANGUAGE OverloadedStrings #-}
module Duckling.Ranking.Classifiers.HE_XX (classifiers) where
import Data.String
import Prelude
import qualified Data.HashMap.Strict as HashMap
import Duckling.Ranking.Types

classifiers :: Classifiers
classifiers
  = HashMap.fromList
      [("\1502\1512\1509",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3025850929940455,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 8},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer (numeric)",
        Classifier{okData =
                     ClassData{prior = -1.0116009116784799,
                               unseen = -3.5263605246161616,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 32},
                   koData =
                     ClassData{prior = -0.45198512374305727,
                               unseen = -4.060443010546419,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 56}}),
       ("\1489 <date>",
        Classifier{okData =
                     ClassData{prior = -0.16034265007517937,
                               unseen = -4.248495242049359,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1502\1512\1509", -3.5409593240373143),
                                    ("week", -3.1354942159291497),
                                    ("<time> <part-of-day>", -3.5409593240373143),
                                    ("dd/mm", -3.5409593240373143),
                                    ("<duration> back", -3.5409593240373143),
                                    ("intersect", -3.1354942159291497),
                                    ("\1488\1493\1490\1493\1505\1496", -3.5409593240373143),
                                    ("day", -2.2881963555419462),
                                    ("this <cycle>", -3.5409593240373143),
                                    ("time-of-day (latent)", -3.1354942159291497),
                                    ("<time-of-day> am|pm", -3.5409593240373143),
                                    ("named-day", -3.1354942159291497),
                                    ("current <day-of-week>", -3.5409593240373143),
                                    ("last <time>", -3.5409593240373143),
                                    ("\1488\1493\1511\1496\1493\1489\1512", -3.5409593240373143),
                                    ("hour", -1.836211231798889), ("month", -2.4423470353692043),
                                    ("\1508\1489\1512\1493\1488\1512", -3.1354942159291497),
                                    ("last <cycle>", -3.5409593240373143),
                                    ("week-end", -3.1354942159291497),
                                    ("this <time>", -3.1354942159291497)],
                               n = 23},
                   koData =
                     ClassData{prior = -1.9095425048844386,
                               unseen = -3.4657359027997265,
                               likelihoods =
                                 HashMap.fromList
                                   [("intersect", -2.740840023925201), ("day", -2.3353749158170367),
                                    ("<day-of-month> (ordinal)", -2.740840023925201),
                                    ("month", -2.3353749158170367),
                                    ("<named-month> year", -2.740840023925201),
                                    ("this <time>", -2.740840023925201)],
                               n = 4}}),
       ("lunch",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer (20..90)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time> <part-of-day>",
        Classifier{okData =
                     ClassData{prior = -9.53101798043249e-2,
                               unseen = -3.4965075614664802,
                               likelihoods =
                                 HashMap.fromList
                                   [("dayhour", -1.3862943611198906),
                                    ("\1489 <date>morning", -2.772588722239781),
                                    ("the this <cycle>evening|night", -2.772588722239781),
                                    ("yesterdayevening|night", -2.772588722239781),
                                    ("hourhour", -2.0794415416798357),
                                    ("time-of-day (latent)morning", -2.772588722239781),
                                    ("named-daymorning", -2.772588722239781),
                                    ("todayevening|night", -2.772588722239781),
                                    ("tomorrowlunch", -2.367123614131617),
                                    ("at <time-of-day>morning", -2.772588722239781),
                                    ("tomorrowevening|night", -2.772588722239781)],
                               n = 10},
                   koData =
                     ClassData{prior = -2.3978952727983707, unseen = -2.70805020110221,
                               likelihoods =
                                 HashMap.fromList
                                   [("dayhour", -1.9459101490553135),
                                    ("<day-of-month> (ordinal)morning", -1.9459101490553135)],
                               n = 1}}),
       ("dd/mm",
        Classifier{okData =
                     ClassData{prior = -1.252762968495368, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -0.3364722366212129,
                               unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5}}),
       ("today",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("at <time-of-day>",
        Classifier{okData =
                     ClassData{prior = -0.2876820724517809,
                               unseen = -2.3025850929940455,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -1.0986122886681098),
                                    ("<time-of-day> am|pm", -1.5040773967762742),
                                    ("hour", -0.8109302162163288)],
                               n = 3},
                   koData =
                     ClassData{prior = -1.3862943611198906, unseen = -1.791759469228055,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -0.916290731874155),
                                    ("hour", -0.916290731874155)],
                               n = 1}}),
       ("<day-of-month> (non ordinal) of <named-month>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.6375861597263857,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)\1488\1493\1490\1493\1505\1496",
                                     -2.917770732084279),
                                    ("integer (numeric)\1504\1493\1489\1502\1489\1512",
                                     -2.917770732084279),
                                    ("integer (numeric)\1497\1493\1500\1497", -2.917770732084279),
                                    ("integer (numeric)\1502\1512\1509", -2.2246235515243336),
                                    ("integer (numeric)\1508\1489\1512\1493\1488\1512",
                                     -1.8191584434161694),
                                    ("integer (numeric)\1488\1508\1512\1497\1500",
                                     -2.917770732084279),
                                    ("integer 3\1502\1512\1509", -2.917770732084279),
                                    ("integer (numeric)\1491\1510\1502\1489\1512",
                                     -2.917770732084279),
                                    ("month", -0.9028677115420143)],
                               n = 14},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.3025850929940455,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<duration> back",
        Classifier{okData =
                     ClassData{prior = -0.916290731874155, unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.3862943611198906),
                                    ("dual <unit-of-duration>", -1.3862943611198906),
                                    ("month", -1.3862943611198906),
                                    ("single <unit-of-duration>", -1.3862943611198906)],
                               n = 2},
                   koData =
                     ClassData{prior = -0.5108256237659907,
                               unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.6094379124341003), ("month", -1.2039728043259361),
                                    ("single <unit-of-duration>", -0.916290731874155)],
                               n = 3}}),
       ("absorption of , after named day",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -0.6931471805599453),
                                    ("named-day", -0.6931471805599453)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("the ides of <named-month>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1502\1512\1509", -0.6931471805599453),
                                    ("month", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("ordinal 4",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3}}),
       ("between <datetime> and <datetime> (interval)",
        Classifier{okData =
                     ClassData{prior = -1.791759469228055, unseen = -3.258096538021482,
                               likelihoods =
                                 HashMap.fromList
                                   [("dayday", -1.6094379124341003),
                                    ("intersectintersect", -1.6094379124341003)],
                               n = 4},
                   koData =
                     ClassData{prior = -0.1823215567939546, unseen = -4.060443010546419,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)<named-month> year", -2.9444389791664407),
                                    ("dayhour", -2.9444389791664407),
                                    ("daymonth", -2.097141118779237),
                                    ("time-of-day (latent)intersect", -2.9444389791664407),
                                    ("hourmonth", -2.097141118779237),
                                    ("dayday", -2.097141118779237),
                                    ("<day-of-month> (ordinal)intersect", -2.9444389791664407),
                                    ("<day-of-month> (ordinal)\1504\1493\1489\1502\1489\1512",
                                     -3.349904087274605),
                                    ("time-of-day (latent)\1491\1510\1502\1489\1512",
                                     -3.349904087274605),
                                    ("time-of-day (latent)\1504\1493\1489\1502\1489\1512",
                                     -3.349904087274605),
                                    ("intersect<day-of-month> (non ordinal) of <named-month>",
                                     -2.9444389791664407),
                                    ("intersecttime-of-day (latent)", -2.9444389791664407),
                                    ("intersect<day-of-month> (ordinal) of <named-month>",
                                     -2.9444389791664407),
                                    ("intersect<day-of-month> (ordinal)", -2.9444389791664407),
                                    ("<day-of-month> (ordinal)\1491\1510\1502\1489\1512",
                                     -3.349904087274605),
                                    ("<day-of-month> (ordinal)<named-month> year",
                                     -2.9444389791664407)],
                               n = 20}}),
       ("\1489 <named-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -0.6931471805599453),
                                    ("named-day", -0.6931471805599453)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("month (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.4849066497880004,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 10},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("hour (grain)",
        Classifier{okData =
                     ClassData{prior = -0.916290731874155, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -0.5108256237659907,
                               unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3}}),
       ("ordinal 9",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("integer 21..99 (with and)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods =
                                 HashMap.fromList [("integer (20..90)integer 4", 0.0)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("intersect",
        Classifier{okData =
                     ClassData{prior = -0.4700036292457356, unseen = -5.062595033026967,
                               likelihoods =
                                 HashMap.fromList
                                   [("hourday", -2.8590212280120886),
                                    ("daymonth", -3.4468078929142076),
                                    ("monthyear", -3.9576335166801986),
                                    ("the <day-of-month> (ordinal)in <named-month>",
                                     -3.9576335166801986),
                                    ("\1488\1493\1511\1496\1493\1489\1512year", -4.363098624788362),
                                    ("intersect<time-of-day> am|pm", -3.9576335166801986),
                                    ("<time> <part-of-day>\1489 <named-day>", -3.6699514442284173),
                                    ("intersect by \",\"<time-of-day> am|pm", -2.8590212280120886),
                                    ("last <day-of-week> of <time>year", -4.363098624788362),
                                    ("dayday", -2.7536607123542622),
                                    ("the <day-of-month> (ordinal)\1489 <date>",
                                     -3.9576335166801986),
                                    ("dayyear", -2.2836570831085266),
                                    ("<day-of-month>(ordinal) <named-month>year",
                                     -3.9576335166801986),
                                    ("\1489 <date>\1489 <named-day>", -4.363098624788362),
                                    ("absorption of , after named day<day-of-month> (ordinal) of <named-month>",
                                     -3.9576335166801986),
                                    ("<day-of-month> (ordinal) of <named-month>year",
                                     -3.264486336120253),
                                    ("named-daynext <cycle>", -4.363098624788362),
                                    ("dayminute", -2.348195604246098),
                                    ("named-day<day-of-month> (ordinal) of <named-month>",
                                     -4.363098624788362),
                                    ("named-day\1489 <date>", -4.363098624788362),
                                    ("absorption of , after named dayintersect",
                                     -3.9576335166801986),
                                    ("named-day<day-of-month> (non ordinal) of <named-month>",
                                     -4.363098624788362),
                                    ("absorption of , after named dayintersect by \",\"",
                                     -3.4468078929142076),
                                    ("year<time-of-day> am|pm", -4.363098624788362),
                                    ("\1489 <date>\1489 <date>", -4.363098624788362),
                                    ("<day-of-month> (non ordinal) of <named-month>year",
                                     -3.264486336120253),
                                    ("absorption of , after named day<day-of-month> (non ordinal) of <named-month>",
                                     -3.9576335166801986),
                                    ("dayweek", -3.9576335166801986),
                                    ("\1502\1512\1509year", -4.363098624788362),
                                    ("<time> <part-of-day>\1489 <date>", -3.6699514442284173),
                                    ("named-daythe <day-of-month> (ordinal)", -4.363098624788362),
                                    ("<day-of-month> (non ordinal) <named-month>year",
                                     -3.9576335166801986),
                                    ("yearminute", -4.363098624788362)],
                               n = 55},
                   koData =
                     ClassData{prior = -0.9808292530117262, unseen = -4.736198448394496,
                               likelihoods =
                                 HashMap.fromList
                                   [("in <named-month>year", -4.034240638152395),
                                    ("dayhour", -3.628775530044231),
                                    ("daymonth", -3.628775530044231),
                                    ("monthyear", -2.6479462770325046),
                                    ("intersecthh:mm", -3.628775530044231),
                                    ("houryear", -3.628775530044231),
                                    ("intersect by \",\"<time-of-day> am|pm", -4.034240638152395),
                                    ("dayday", -4.034240638152395),
                                    ("intersect by \",\"hh:mm", -2.424802725718295),
                                    ("dayyear", -3.628775530044231),
                                    ("monthminute", -3.628775530044231),
                                    ("\1491\1510\1502\1489\1512year", -4.034240638152395),
                                    ("\1488\1508\1512\1497\1500year", -4.034240638152395),
                                    ("named-dayin <named-month>", -4.034240638152395),
                                    ("\1504\1493\1489\1502\1489\1512year", -4.034240638152395),
                                    ("dayminute", -2.0193376176101303),
                                    ("named-day\1489 <date>", -4.034240638152395),
                                    ("absorption of , after named dayintersect",
                                     -3.628775530044231),
                                    ("yearhh:mm", -4.034240638152395),
                                    ("absorption of , after named dayintersect by \",\"",
                                     -3.628775530044231),
                                    ("between <datetime> and <datetime> (interval)year",
                                     -3.1179499062782403),
                                    ("\1502\1512\1509year", -3.628775530044231),
                                    ("\1489 <date>year", -4.034240638152395),
                                    ("named-daythe <day-of-month> (ordinal)", -4.034240638152395),
                                    ("tomorrownoon", -3.628775530044231),
                                    ("yearminute", -4.034240638152395)],
                               n = 33}}),
       ("year (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("next <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.70805020110221,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.540445040947149),
                                    ("month (grain)", -1.9459101490553135),
                                    ("year (grain)", -1.9459101490553135),
                                    ("week (grain)", -1.540445040947149),
                                    ("year", -1.9459101490553135), ("month", -1.9459101490553135)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("yyyy-mm-dd",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("evening|night",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("ordinal 3",
        Classifier{okData =
                     ClassData{prior = -1.0986122886681098,
                               unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -0.40546510810816444,
                               unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4}}),
       ("dd/mm/yyyy",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("yesterday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("hh:mm:ss",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<day-of-month> (ordinal) of <named-month>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.713572066704308,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinal 3\1502\1512\1509", -2.995732273553991),
                                    ("ordinal (digits)\1504\1493\1489\1502\1489\1512",
                                     -2.995732273553991),
                                    ("ordinal (digits)\1488\1493\1490\1493\1505\1496",
                                     -2.995732273553991),
                                    ("ordinal (digits)\1502\1512\1509", -2.3025850929940455),
                                    ("ordinal (digits)\1488\1508\1512\1497\1500",
                                     -2.995732273553991),
                                    ("ordinal (digits)\1497\1493\1500\1497", -2.995732273553991),
                                    ("ordinal 3\1488\1493\1511\1496\1493\1489\1512",
                                     -2.995732273553991),
                                    ("month", -0.916290731874155),
                                    ("ordinal (digits)\1491\1510\1502\1489\1512",
                                     -2.995732273553991),
                                    ("ordinal (digits)\1508\1489\1512\1493\1488\1512",
                                     -1.8971199848858813)],
                               n = 15},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.3978952727983707,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<hour-of-day> and <integer>",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)integer 4", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1}}),
       ("quarter to|till|before <integer> (hour-of-day)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<hour-of-day> <integer>",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)integer 10", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1}}),
       ("\1504\1493\1489\1502\1489\1512",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("ordinal 19",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1488\1493\1490\1493\1505\1496",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1488\1508\1512\1497\1500",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("week (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 9},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("now",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer 11..19",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("integer 9integer 10", 0.0)],
                               n = 1}}),
       ("integer 7",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<day-of-month>(ordinal) <named-month>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.367295829986474,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinal 3\1489 <date>", -2.2335922215070942),
                                    ("ordinal (digits)\1488\1508\1512\1497\1500",
                                     -2.639057329615259),
                                    ("ordinal (digits)in <named-month>", -1.9459101490553135),
                                    ("month", -0.8472978603872037),
                                    ("ordinal 3in <named-month>", -2.2335922215070942),
                                    ("ordinal (digits)\1489 <date>", -1.9459101490553135)],
                               n = 11},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1497\1493\1500\1497",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("numbers prefix with -, negative or minus",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 6}}),
       ("tomorrow",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1491\1510\1502\1489\1512",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("ordinal 2",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6}}),
       ("next <day-of-week>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -0.6931471805599453),
                                    ("named-day", -0.6931471805599453)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("half an hour",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("the <day-of-month> (ordinal)",
        Classifier{okData =
                     ClassData{prior = -0.2876820724517809,
                               unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinal 3", -1.252762968495368),
                                    ("ordinal 19", -1.252762968495368),
                                    ("ordinal (digits)", -1.252762968495368)],
                               n = 3},
                   koData =
                     ClassData{prior = -1.3862943611198906, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("ordinal 9", -0.916290731874155)],
                               n = 1}}),
       ("fractional number",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6}}),
       ("this <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -0.6931471805599453),
                                    ("week (grain)", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("minute (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("ordinal 7",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("time-of-day (latent)",
        Classifier{okData =
                     ClassData{prior = -1.2237754316221157,
                               unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.4700036292457356),
                                    ("integer 9", -1.3862943611198906)],
                               n = 5},
                   koData =
                     ClassData{prior = -0.3483066942682157, unseen = -2.772588722239781,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.3101549283038396),
                                    ("integer (20..90)", -2.0149030205422647),
                                    ("integer 9", -2.0149030205422647)],
                               n = 12}}),
       ("year",
        Classifier{okData =
                     ClassData{prior = -0.3364722366212129,
                               unseen = -2.4849066497880004,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 10},
                   koData =
                     ClassData{prior = -1.252762968495368, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 4}}),
       ("integer 9",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("last <day-of-week> of <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("daymonth", -0.8754687373538999),
                                    ("named-day<named-month> year", -1.791759469228055),
                                    ("named-dayintersect", -1.791759469228055),
                                    ("named-day\1502\1512\1509", -1.3862943611198906)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<integer> <unit-of-duration>",
        Classifier{okData =
                     ClassData{prior = -0.11778303565638351,
                               unseen = -3.367295829986474,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.639057329615259),
                                    ("integer 21..99 (with and)hour (grain)", -2.639057329615259),
                                    ("integer 3month (grain)", -2.639057329615259),
                                    ("day", -2.2335922215070942),
                                    ("integer 7day (grain)", -2.2335922215070942),
                                    ("integer (numeric)week (grain)", -2.639057329615259),
                                    ("hour", -2.2335922215070942), ("month", -2.639057329615259),
                                    ("integer (numeric)minute (grain)", -2.2335922215070942),
                                    ("minute", -2.2335922215070942),
                                    ("integer (numeric)hour (grain)", -2.639057329615259)],
                               n = 8},
                   koData =
                     ClassData{prior = -2.1972245773362196, unseen = -2.70805020110221,
                               likelihoods =
                                 HashMap.fromList
                                   [("hour", -1.9459101490553135),
                                    ("integer 4hour (grain)", -1.9459101490553135)],
                               n = 1}}),
       ("dual <unit-of-duration>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.3862943611198906),
                                    ("month (grain)", -1.3862943611198906),
                                    ("week (grain)", -1.3862943611198906),
                                    ("month", -1.3862943611198906)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time-of-day> am|pm",
        Classifier{okData =
                     ClassData{prior = -0.3629054936893685,
                               unseen = -3.6635616461296463,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1489 <date>", -2.9444389791664407),
                                    ("at <time-of-day>", -2.9444389791664407),
                                    ("time-of-day (latent)", -2.2512917986064953),
                                    ("hh:mm", -1.1526795099383855), ("hour", -1.845826690498331),
                                    ("minute", -1.1526795099383855)],
                               n = 16},
                   koData =
                     ClassData{prior = -1.1895840668738362, unseen = -3.044522437723423,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -0.916290731874155),
                                    ("hour", -0.916290731874155)],
                               n = 7}}),
       ("integer 10",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("intersect by \",\"",
        Classifier{okData =
                     ClassData{prior = -0.4595323293784402,
                               unseen = -4.2626798770413155,
                               likelihoods =
                                 HashMap.fromList
                                   [("<day-of-month> (ordinal) of <named-month>intersect",
                                     -3.5553480614894135),
                                    ("intersect by \",\"year", -3.1498829533812494),
                                    ("dayday", -2.3025850929940455),
                                    ("named-dayintersect by \",\"", -2.639057329615259),
                                    ("dayyear", -2.05127066471314),
                                    ("<day-of-month>(ordinal) <named-month>year",
                                     -3.5553480614894135),
                                    ("intersect by \",\"intersect", -3.1498829533812494),
                                    ("<day-of-month> (ordinal) of <named-month>year",
                                     -3.5553480614894135),
                                    ("named-dayintersect", -3.1498829533812494),
                                    ("<day-of-month> (non ordinal) of <named-month>intersect",
                                     -3.5553480614894135),
                                    ("dayminute", -1.8505999692509885),
                                    ("named-day<day-of-month> (ordinal) of <named-month>",
                                     -3.1498829533812494),
                                    ("intersectyear", -3.1498829533812494),
                                    ("named-day<day-of-month> (non ordinal) of <named-month>",
                                     -3.1498829533812494),
                                    ("<day-of-month> (non ordinal) of <named-month>year",
                                     -3.5553480614894135),
                                    ("intersectintersect", -3.1498829533812494),
                                    ("<day-of-month> (non ordinal) <named-month>year",
                                     -3.5553480614894135)],
                               n = 24},
                   koData =
                     ClassData{prior = -0.9985288301111273,
                               unseen = -3.9318256327243257,
                               likelihoods =
                                 HashMap.fromList
                                   [("monthyear", -2.8134107167600364),
                                    ("<day-of-month> (ordinal) of <named-month>intersect",
                                     -3.2188758248682006),
                                    ("named-dayintersect by \",\"", -2.8134107167600364),
                                    ("monthminute", -2.8134107167600364),
                                    ("\1497\1493\1500\1497year", -3.2188758248682006),
                                    ("\1488\1508\1512\1497\1500year", -3.2188758248682006),
                                    ("\1497\1493\1500\1497intersect", -2.8134107167600364),
                                    ("intersect by \",\"intersect", -2.8134107167600364),
                                    ("named-dayintersect", -2.8134107167600364),
                                    ("<day-of-month> (non ordinal) of <named-month>intersect",
                                     -3.2188758248682006),
                                    ("dayminute", -1.5141277326297755),
                                    ("intersectintersect", -2.8134107167600364)],
                               n = 14}}),
       ("hh:mm",
        Classifier{okData =
                     ClassData{prior = -7.410797215372185e-2,
                               unseen = -2.70805020110221,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 13},
                   koData =
                     ClassData{prior = -2.639057329615259, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("named-day",
        Classifier{okData =
                     ClassData{prior = -3.7740327982847086e-2,
                               unseen = -3.332204510175204,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 26},
                   koData =
                     ClassData{prior = -3.295836866004329, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("ordinal 1",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7}}),
       ("current <day-of-week>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.70805020110221,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1489 <date>", -1.9459101490553135),
                                    ("\1489 <named-day>", -1.9459101490553135),
                                    ("day", -0.8472978603872037),
                                    ("named-day", -1.252762968495368)],
                               n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer 4",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("quarter of an hour",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<named-day> <day-of-month> (ordinal)",
        Classifier{okData =
                     ClassData{prior = -1.0986122886681098, unseen = -1.791759469228055,
                               likelihoods =
                                 HashMap.fromList
                                   [("named-dayordinal (digits)", -0.916290731874155),
                                    ("day", -0.916290731874155)],
                               n = 1},
                   koData =
                     ClassData{prior = -0.40546510810816444,
                               unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("absorption of , after named dayordinal (digits)",
                                     -0.8472978603872037),
                                    ("day", -0.8472978603872037)],
                               n = 2}}),
       ("the this <cycle>",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("month (grain)", -1.6094379124341003),
                                    ("day", -1.2039728043259361), ("month", -1.6094379124341003),
                                    ("day (grain)", -1.2039728043259361)],
                               n = 3},
                   koData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("month (grain)", -1.6094379124341003),
                                    ("day", -1.2039728043259361), ("month", -1.6094379124341003),
                                    ("day (grain)", -1.2039728043259361)],
                               n = 3}}),
       ("<duration> ago",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.639057329615259,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.466337068793427), ("day", -1.8718021769015913),
                                    ("<integer> <unit-of-duration>", -1.1786549963416462),
                                    ("month", -1.8718021769015913),
                                    ("single <unit-of-duration>", -1.8718021769015913)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("ordinal 6",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4}}),
       ("integer 3",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("last <time>",
        Classifier{okData =
                     ClassData{prior = -0.9808292530117262,
                               unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1489 <date>", -1.791759469228055),
                                    ("day", -1.791759469228055), ("named-day", -1.791759469228055),
                                    ("hour", -1.3862943611198906),
                                    ("week-end", -1.791759469228055)],
                               n = 3},
                   koData =
                     ClassData{prior = -0.4700036292457356, unseen = -2.833213344056216,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -0.9808292530117262),
                                    ("named-day", -1.6739764335716716),
                                    ("<day-of-month> (ordinal)", -1.3862943611198906)],
                               n = 5}}),
       ("<day-of-month> (ordinal)",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -2.70805020110221,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinal 4", -1.9459101490553135),
                                    ("ordinal 3", -1.9459101490553135),
                                    ("ordinal 2", -1.252762968495368),
                                    ("ordinal 1", -1.540445040947149),
                                    ("ordinal (digits)", -1.540445040947149)],
                               n = 9}}),
       ("\1488\1493\1511\1496\1493\1489\1512",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("noon",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("\1508\1489\1512\1493\1488\1512",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("next <time>",
        Classifier{okData =
                     ClassData{prior = -1.3862943611198906,
                               unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1502\1512\1509", -1.0986122886681098),
                                    ("month", -1.0986122886681098)],
                               n = 1},
                   koData =
                     ClassData{prior = -0.2876820724517809,
                               unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -0.916290731874155), ("named-day", -0.916290731874155)],
                               n = 3}}),
       ("last <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.2188758248682006,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.791759469228055),
                                    ("month (grain)", -1.3862943611198906),
                                    ("year (grain)", -2.4849066497880004),
                                    ("week (grain)", -1.791759469228055),
                                    ("year", -2.4849066497880004), ("month", -1.3862943611198906)],
                               n = 9},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("ordinal 20..90",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("hhmm (military) am|pm",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("in <duration>",
        Classifier{okData =
                     ClassData{prior = -0.2231435513142097, unseen = -3.295836866004329,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -2.5649493574615367),
                                    ("half an hour", -2.5649493574615367),
                                    ("<integer> <unit-of-duration>", -1.466337068793427),
                                    ("dual <unit-of-duration>", -2.5649493574615367),
                                    ("quarter of an hour", -2.5649493574615367),
                                    ("hour", -2.159484249353372), ("month", -2.5649493574615367),
                                    ("minute", -1.6486586255873816)],
                               n = 8},
                   koData =
                     ClassData{prior = -1.6094379124341003, unseen = -2.70805020110221,
                               likelihoods =
                                 HashMap.fromList
                                   [("quarter", -1.9459101490553135),
                                    ("month", -1.9459101490553135),
                                    ("single <unit-of-duration>", -1.540445040947149)],
                               n = 2}}),
       ("in <named-month>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.772588722239781,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1502\1512\1509", -2.0149030205422647),
                                    ("\1488\1493\1490\1493\1505\1496", -2.0149030205422647),
                                    ("\1488\1493\1511\1496\1493\1489\1512", -2.0149030205422647),
                                    ("month", -0.916290731874155),
                                    ("\1508\1489\1512\1493\1488\1512", -1.6094379124341003)],
                               n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<named-month> year",
        Classifier{okData =
                     ClassData{prior = -1.2039728043259361, unseen = -2.772588722239781,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1502\1512\1509", -2.0149030205422647),
                                    ("\1488\1493\1490\1493\1505\1496", -2.0149030205422647),
                                    ("\1488\1493\1511\1496\1493\1489\1512", -2.0149030205422647),
                                    ("month", -1.3217558399823195)],
                               n = 3},
                   koData =
                     ClassData{prior = -0.35667494393873245,
                               unseen = -3.1780538303479458,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1502\1512\1509", -2.03688192726104),
                                    ("\1489 <date>", -2.4423470353692043),
                                    ("\1504\1493\1489\1502\1489\1512", -2.4423470353692043),
                                    ("\1488\1508\1512\1497\1500", -2.4423470353692043),
                                    ("\1491\1510\1502\1489\1512", -2.4423470353692043),
                                    ("month", -1.0560526742493137),
                                    ("in <named-month>", -2.4423470353692043)],
                               n = 7}}),
       ("half",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("ordinal 5",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("<day-of-month> (non ordinal) <named-month>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.2188758248682006,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)in <named-month>", -1.791759469228055),
                                    ("integer (numeric)\1488\1508\1512\1497\1500",
                                     -2.4849066497880004),
                                    ("integer 3\1489 <date>", -2.4849066497880004),
                                    ("integer (numeric)\1489 <date>", -1.791759469228055),
                                    ("month", -0.8754687373538999),
                                    ("integer 3in <named-month>", -2.4849066497880004)],
                               n = 9},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("ordinal (digits)",
        Classifier{okData =
                     ClassData{prior = -0.496436886313891, unseen = -2.772588722239781,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 14},
                   koData =
                     ClassData{prior = -0.9382696385929302,
                               unseen = -2.3978952727983707,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 9}}),
       ("quarter (grain)",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3}}),
       ("<day-of-month>(ordinal) <named-month> year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinal 3\1489 <date>", -1.252762968495368),
                                    ("month", -0.8472978603872037),
                                    ("ordinal 3in <named-month>", -1.252762968495368)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("morning",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("week-end",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("this evening",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("day (grain)",
        Classifier{okData =
                     ClassData{prior = -0.5596157879354228, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -0.8472978603872037,
                               unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3}}),
       ("single <unit-of-duration>",
        Classifier{okData =
                     ClassData{prior = -2.9444389791664407,
                               unseen = -2.9444389791664407,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.1972245773362196),
                                    ("month (grain)", -2.1972245773362196),
                                    ("week (grain)", -2.1972245773362196),
                                    ("month", -2.1972245773362196)],
                               n = 2},
                   koData =
                     ClassData{prior = -5.406722127027582e-2,
                               unseen = -4.465908118654584,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.257122718917288),
                                    ("month (grain)", -2.151762203259462),
                                    ("hour (grain)", -2.662587827025453),
                                    ("year (grain)", -3.355735007585398),
                                    ("week (grain)", -2.257122718917288),
                                    ("day", -2.374905754573672), ("quarter", -3.068052935133617),
                                    ("minute (grain)", -3.355735007585398),
                                    ("year", -3.355735007585398), ("hour", -2.662587827025453),
                                    ("month", -2.151762203259462),
                                    ("quarter (grain)", -3.068052935133617),
                                    ("minute", -3.355735007585398),
                                    ("day (grain)", -2.374905754573672)],
                               n = 36}}),
       ("this <time>",
        Classifier{okData =
                     ClassData{prior = -0.45198512374305727,
                               unseen = -3.0910424533583156,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1489 <date>", -1.9459101490553135),
                                    ("\1489 <named-day>", -2.3513752571634776),
                                    ("day", -1.252762968495368), ("named-day", -1.6582280766035324),
                                    ("hour", -1.9459101490553135),
                                    ("week-end", -2.3513752571634776)],
                               n = 7},
                   koData =
                     ClassData{prior = -1.0116009116784799, unseen = -2.772588722239781,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1489 <date>", -2.0149030205422647),
                                    ("day", -1.0986122886681098),
                                    ("<day-of-month> (ordinal)", -1.3217558399823195)],
                               n = 4}})]