-- Copyright (c) 2016-present, Facebook, Inc.
-- All rights reserved.
--
-- This source code is licensed under the BSD-style license found in the
-- LICENSE file in the root directory of this source tree. An additional grant
-- of patent rights can be found in the PATENTS file in the same directory.

-----------------------------------------------------------------
-- Auto-generated by regenClassifiers
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
--  @generated
-----------------------------------------------------------------
{-# LANGUAGE OverloadedStrings #-}
module Duckling.Ranking.Classifiers.RU_XX (classifiers) where
import Data.String
import Prelude
import qualified Data.HashMap.Strict as HashMap
import Duckling.Ranking.Types

classifiers :: Classifiers
classifiers
  = HashMap.fromList
      [("week",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1055\1086\1085\1077\1076\1077\1083\1100\1085\1080\1082",
        Classifier{okData =
                     ClassData{prior = -0.1823215567939546,
                               unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -1.791759469228055, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("<time> timezone",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("hh:mm", -0.6931471805599453),
                                    ("minute", -0.6931471805599453)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer (numeric)",
        Classifier{okData =
                     ClassData{prior = -0.8009798853631607, unseen = -4.634728988229636,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 101},
                   koData =
                     ClassData{prior = -0.5958188365993833, unseen = -4.836281906951478,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 124}}),
       ("\1057\1088\1077\1076\1072",
        Classifier{okData =
                     ClassData{prior = -0.40546510810816444,
                               unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -1.0986122886681098,
                               unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("integer (3..19)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.639057329615259,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 12},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("lunch",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1087\1086\1079\1072\1087\1086\1079\1072\1074\1095\1077\1088\1072",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer (20..90)",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5}}),
       ("\1074\1095\1077\1088\1072",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time> <part-of-day>",
        Classifier{okData =
                     ClassData{prior = -0.20909179785855936,
                               unseen = -4.770684624465665,
                               likelihoods =
                                 HashMap.fromList
                                   [("<time-of-day>  o'clockmorning", -3.6635616461296463),
                                    ("until <time-of-day>afternoon", -4.069026754237811),
                                    ("dayhour", -2.816263785742443),
                                    ("on <date>evening", -4.069026754237811),
                                    ("at <time-of-day>evening", -4.069026754237811),
                                    ("intersect by ','evening", -3.6635616461296463),
                                    ("intersectevening", -2.277267285009756),
                                    ("hourhour", -1.2656663733312759),
                                    ("\1079\1072\1074\1090\1088\1072lunch", -4.069026754237811),
                                    ("on <date>afternoon", -3.6635616461296463),
                                    ("at <time-of-day>afternoon", -3.6635616461296463),
                                    ("<time-of-day>  o'clockafternoon", -2.9704144655697013),
                                    ("until <time-of-day>morning", -4.069026754237811),
                                    ("minutehour", -2.9704144655697013),
                                    ("time-of-day (latent)morning", -4.069026754237811),
                                    ("hh:mmmorning", -4.069026754237811),
                                    ("\1074\1095\1077\1088\1072evening", -4.069026754237811),
                                    ("time-of-day (latent)evening", -4.069026754237811),
                                    ("\1079\1072\1074\1090\1088\1072evening", -4.069026754237811),
                                    ("\1089\1077\1075\1086\1076\1085\1103afternoon",
                                     -3.6635616461296463),
                                    ("<time-of-day>  o'clockevening", -3.6635616461296463),
                                    ("\1089\1077\1075\1086\1076\1085\1103evening",
                                     -4.069026754237811),
                                    ("hh:mmnight", -4.069026754237811),
                                    ("hh:mmafternoon", -4.069026754237811),
                                    ("on <date>morning", -4.069026754237811),
                                    ("at <time-of-day>morning", -4.069026754237811)],
                               n = 43},
                   koData =
                     ClassData{prior = -1.667706820558076, unseen = -3.951243718581427,
                               likelihoods =
                                 HashMap.fromList
                                   [("dayhour", -3.2386784521643803),
                                    ("yearhour", -2.833213344056216),
                                    ("intersectevening", -2.5455312716044354),
                                    ("hourhour", -1.8523840910444898),
                                    ("<day-of-month> (ordinal)morning", -3.2386784521643803),
                                    ("year (latent)afternoon", -3.2386784521643803),
                                    ("year (latent)night", -3.2386784521643803),
                                    ("time-of-day (latent)afternoon", -2.322387720290225)],
                               n = 10}}),
       ("numbers prefix with -, minus",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -3.2188758248682006,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.4700036292457356),
                                    ("decimal number", -0.9808292530117262)],
                               n = 22}}),
       ("mm/dd",
        Classifier{okData =
                     ClassData{prior = -0.7801585575495751,
                               unseen = -2.5649493574615367,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 11},
                   koData =
                     ClassData{prior = -0.6131044728864089, unseen = -2.70805020110221,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 13}}),
       ("at <time-of-day>",
        Classifier{okData =
                     ClassData{prior = -8.4557388028063e-2, unseen = -4.31748811353631,
                               likelihoods =
                                 HashMap.fromList
                                   [("<time-of-day>  o'clock", -1.8191584434161694),
                                    ("time-of-day (latent)", -1.3083328196501787),
                                    ("hh:mm", -2.917770732084279), ("noon", -3.6109179126442243),
                                    ("hour", -0.8383291904044432), ("minute", -2.917770732084279)],
                               n = 34},
                   koData =
                     ClassData{prior = -2.512305623976115, unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -1.0986122886681098),
                                    ("hour", -1.0986122886681098)],
                               n = 3}}),
       ("absorption of , after named day",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.2188758248682006,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1055\1086\1085\1077\1076\1077\1083\1100\1085\1080\1082",
                                     -2.0794415416798357),
                                    ("\1057\1088\1077\1076\1072", -2.0794415416798357),
                                    ("\1042\1086\1089\1082\1088\1077\1089\1077\1085\1100\1077",
                                     -2.4849066497880004),
                                    ("day", -0.8754687373538999),
                                    ("\1057\1091\1073\1073\1086\1090\1072", -2.4849066497880004),
                                    ("\1055\1103\1090\1085\1080\1094\1072", -1.791759469228055)],
                               n = 9},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("on <date>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.653960350157523,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1055\1086\1085\1077\1076\1077\1083\1100\1085\1080\1082",
                                     -3.951243718581427),
                                    ("<time> <part-of-day>", -3.0349529867072724),
                                    ("<time-of-day>  o'clock", -2.159484249353372),
                                    ("intersect", -2.5649493574615367),
                                    ("day", -2.6984807500860595),
                                    ("time-of-day (latent)", -2.005333569526114),
                                    ("\1057\1091\1073\1073\1086\1090\1072", -3.545778610473263),
                                    ("hh:mm", -3.258096538021482),
                                    ("\1042\1090\1086\1088\1085\1080\1082", -3.951243718581427),
                                    ("\1055\1103\1090\1085\1080\1094\1072", -3.951243718581427),
                                    ("noon", -3.951243718581427), ("hour", -1.0608719606852628),
                                    ("this|next <day-of-week>", -3.951243718581427),
                                    ("minute", -3.0349529867072724)],
                               n = 45},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.70805020110221,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1050\1086\1085\1077\1094 \1084\1077\1089\1103\1094\1072",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1074\1077\1089\1085\1072",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer 1",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("between <time-of-day> and <time-of-day> (interval)",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)time-of-day (latent)",
                                     -0.6931471805599453),
                                    ("hourhour", -0.6931471805599453)],
                               n = 1}}),
       ("month (grain)",
        Classifier{okData =
                     ClassData{prior = -0.1823215567939546,
                               unseen = -2.4849066497880004,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 10},
                   koData =
                     ClassData{prior = -1.791759469228055, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("<time-of-day>  o'clock",
        Classifier{okData =
                     ClassData{prior = -0.13102826240640414,
                               unseen = -4.672828834461907,
                               likelihoods =
                                 HashMap.fromList
                                   [("at <time-of-day>", -2.178532444324067),
                                    ("on <date>", -2.178532444324067),
                                    ("time-of-day (latent)", -1.5279448781829175),
                                    ("until <time-of-day>", -3.2771447329921766),
                                    ("hour", -0.7316134613877414),
                                    ("after <time-of-day>", -3.2771447329921766)],
                               n = 50},
                   koData =
                     ClassData{prior = -2.097141118779237, unseen = -3.044522437723423,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -0.916290731874155),
                                    ("hour", -0.916290731874155)],
                               n = 7}}),
       ("\1053\1086\1074\1099\1081 \1075\1086\1076",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1087\1086\1079\1072\1074\1095\1077\1088\1072",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1083\1077\1090\1086",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("hour (grain)",
        Classifier{okData =
                     ClassData{prior = -1.580450375560848, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -0.23052365861183238,
                               unseen = -3.367295829986474,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 27}}),
       ("<ordinal> quarter",
        Classifier{okData =
                     ClassData{prior = -1.0986122886681098,
                               unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..19th)quarter (grain)", -0.6931471805599453),
                                    ("quarter", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -0.40546510810816444,
                               unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..19th)quarter (grain)", -0.6931471805599453),
                                    ("quarter", -0.6931471805599453)],
                               n = 2}}),
       ("intersect",
        Classifier{okData =
                     ClassData{prior = -0.18924199963852842,
                               unseen = -6.056784013228625,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1057\1088\1077\1076\1072\1054\1082\1090\1103\1073\1088\1100",
                                     -4.955827057601261),
                                    ("\1089\1077\1075\1086\1076\1085\1103on <date>",
                                     -4.66814498514948),
                                    ("<day-of-month> (ordinal)\1040\1074\1075\1091\1089\1090",
                                     -5.3612921657094255),
                                    ("hourday", -4.108529197214057),
                                    ("<datetime> - <datetime> (interval)year", -5.3612921657094255),
                                    ("\1063\1077\1090\1074\1077\1088\1075<time> timezone",
                                     -4.955827057601261),
                                    ("hh:mm<part-of-day> of <time>", -4.44500143383527),
                                    ("dayhour", -2.204291744559312),
                                    ("daymonth", -2.4168531865429848),
                                    ("monthyear", -3.4894899888078337),
                                    ("yearhour", -5.3612921657094255),
                                    ("intersect<time-of-day>  o'clock", -4.44500143383527),
                                    ("absorption of , after named daymm/dd/yyyy",
                                     -5.3612921657094255),
                                    ("intersect<time> <part-of-day>", -4.44500143383527),
                                    ("intersect by ','year", -4.955827057601261),
                                    ("<day-of-month> (ordinal)\1060\1077\1074\1088\1072\1083\1100",
                                     -3.4153820166541116),
                                    ("on <date><time-of-day>  o'clock", -4.955827057601261),
                                    ("<day-of-month> (ordinal)\1054\1082\1090\1103\1073\1088\1100",
                                     -4.955827057601261),
                                    ("mm/dd<time-of-day>  o'clock", -4.955827057601261),
                                    ("<day-of-month> (ordinal)\1042\1090\1086\1088\1085\1080\1082",
                                     -5.3612921657094255),
                                    ("on <date>at <time-of-day>", -4.66814498514948),
                                    ("\1079\1072\1074\1090\1088\1072on <date>",
                                     -5.3612921657094255),
                                    ("dayday", -3.0587070727153796),
                                    ("at <time-of-day>\1079\1072\1074\1090\1088\1072",
                                     -5.3612921657094255),
                                    ("mm/ddat <time-of-day>", -4.955827057601261),
                                    ("<day-of-month> (ordinal)intersect", -3.6565440734709997),
                                    ("on <date>\1079\1072\1074\1090\1088\1072",
                                     -5.3612921657094255),
                                    ("hh:mmintersect by ','", -5.3612921657094255),
                                    ("<day-of-month> (ordinal)\1040\1087\1088\1077\1083\1100",
                                     -5.3612921657094255),
                                    ("<day-of-month> (ordinal)\1052\1072\1088\1090",
                                     -4.2626798770413155),
                                    ("intersect<day-of-month> (non ordinal) <named-month>",
                                     -4.955827057601261),
                                    ("dayyear", -2.653241964607215),
                                    ("<day-of-month> (non ordinal) <named-month>intersect",
                                     -5.3612921657094255),
                                    ("\1057\1077\1085\1090\1103\1073\1088\1100year",
                                     -5.3612921657094255),
                                    ("<day-of-month>(ordinal) <named-month>year",
                                     -3.9749978045895347),
                                    ("\1053\1086\1103\1073\1088\1100year", -5.3612921657094255),
                                    ("absorption of , after named day<day-of-month>(ordinal) <named-month>",
                                     -5.3612921657094255),
                                    ("minutehour", -4.108529197214057),
                                    ("absorption of , after named day<day-of-month> (non ordinal) <named-month>",
                                     -3.9749978045895347),
                                    ("\1057\1088\1077\1076\1072intersect", -5.3612921657094255),
                                    ("<day-of-month> (ordinal)\1057\1088\1077\1076\1072",
                                     -5.3612921657094255),
                                    ("\1089\1077\1075\1086\1076\1085\1103<time> <part-of-day>",
                                     -4.955827057601261),
                                    ("<day-of-month> (ordinal)\1052\1072\1081",
                                     -5.3612921657094255),
                                    ("\1089\1077\1075\1086\1076\1085\1103at <time-of-day>",
                                     -4.44500143383527),
                                    ("hh:mmintersect", -5.3612921657094255),
                                    ("\1054\1082\1090\1103\1073\1088\1100year",
                                     -4.2626798770413155),
                                    ("intersect by ','intersect", -5.3612921657094255),
                                    ("absorption of , after named day<day-of-month> (ordinal)",
                                     -5.3612921657094255),
                                    ("dayminute", -4.44500143383527),
                                    ("<time> <part-of-day>intersect", -5.3612921657094255),
                                    ("intersect by ','\1060\1077\1074\1088\1072\1083\1100",
                                     -5.3612921657094255),
                                    ("intersectyear", -3.4894899888078337),
                                    ("\1040\1087\1088\1077\1083\1100year", -5.3612921657094255),
                                    ("minuteday", -4.108529197214057),
                                    ("absorption of , after named dayintersect",
                                     -4.2626798770413155),
                                    ("\1079\1072\1074\1090\1088\1072<time-of-day>  o'clock",
                                     -4.955827057601261),
                                    ("intersect\1060\1077\1074\1088\1072\1083\1100",
                                     -5.3612921657094255),
                                    ("year<time-of-day>  o'clock", -5.3612921657094255),
                                    ("intersect\1054\1082\1090\1103\1073\1088\1100",
                                     -5.3612921657094255),
                                    ("<time-of-day>  o'clock\1079\1072\1074\1090\1088\1072",
                                     -4.66814498514948),
                                    ("\1057\1091\1073\1073\1086\1090\1072on <date>",
                                     -5.3612921657094255),
                                    ("intersect by ','<time> <part-of-day>", -5.3612921657094255),
                                    ("\1057\1091\1073\1073\1086\1090\1072at <time-of-day>",
                                     -4.66814498514948),
                                    ("<time> <part-of-day>intersect by ','", -5.3612921657094255),
                                    ("<time> <part-of-day>\1057\1091\1073\1073\1086\1090\1072",
                                     -5.3612921657094255),
                                    ("\1042\1090\1086\1088\1085\1080\1082next <cycle>",
                                     -5.3612921657094255),
                                    ("mm/ddyear", -4.955827057601261),
                                    ("intersect by ','<time-of-day>  o'clock", -5.3612921657094255),
                                    ("absorption of , after named daymm/dd", -5.3612921657094255),
                                    ("mm/ddon <date>", -5.3612921657094255),
                                    ("<time> <part-of-day>absorption of , after named day",
                                     -5.3612921657094255),
                                    ("intersectintersect", -4.955827057601261),
                                    ("<part-of-day> of <time><day-of-month> (non ordinal) <named-month>",
                                     -5.3612921657094255),
                                    ("\1057\1091\1073\1073\1086\1090\1072<time-of-day>  o'clock",
                                     -4.955827057601261),
                                    ("on <date>on <date>", -5.3612921657094255),
                                    ("dayweek", -5.3612921657094255),
                                    ("\1079\1072\1074\1090\1088\1072at <time-of-day>",
                                     -4.955827057601261),
                                    ("weekyear", -5.3612921657094255),
                                    ("\1052\1072\1081year", -5.3612921657094255),
                                    ("last <cycle> of <time>year", -5.3612921657094255),
                                    ("\1089\1077\1075\1086\1076\1085\1103<time-of-day>  o'clock",
                                     -4.955827057601261),
                                    ("<day-of-month> (non ordinal) <named-month>year",
                                     -4.2626798770413155),
                                    ("\1052\1072\1088\1090year", -4.66814498514948)],
                               n = 168},
                   koData =
                     ClassData{prior = -1.7578579175523736, unseen = -5.081404364984463,
                               likelihoods =
                                 HashMap.fromList
                                   [("dayhour", -4.382026634673881),
                                    ("daymonth", -2.772588722239781),
                                    ("monthyear", -3.283414346005772),
                                    ("yearhour", -4.382026634673881),
                                    ("intersect<time-of-day>  o'clock", -4.382026634673881),
                                    ("intersect<time> <part-of-day>", -4.382026634673881),
                                    ("<day-of-month> (ordinal)\1060\1077\1074\1088\1072\1083\1100",
                                     -3.6888794541139363),
                                    ("<day-of-month> (ordinal)\1054\1082\1090\1103\1073\1088\1100",
                                     -4.382026634673881),
                                    ("monthhour", -3.6888794541139363),
                                    ("hourmonth", -4.382026634673881),
                                    ("<day-of-month> (ordinal)\1042\1090\1086\1088\1085\1080\1082",
                                     -4.382026634673881),
                                    ("dayday", -3.6888794541139363),
                                    ("<day-of-month> (ordinal)intersect", -3.6888794541139363),
                                    ("dayyear", -2.6772785424354564),
                                    ("<day-of-month>(ordinal) <named-month>year",
                                     -3.9765615265657175),
                                    ("\1048\1102\1083\1100year", -3.9765615265657175),
                                    ("between <time-of-day> and <time-of-day> (interval)\1048\1102\1083\1100",
                                     -4.382026634673881),
                                    ("\1057\1088\1077\1076\1072intersect", -4.382026634673881),
                                    ("<day-of-month> (ordinal)\1057\1088\1077\1076\1072",
                                     -4.382026634673881),
                                    ("\1048\1102\1083\1100intersect", -4.382026634673881),
                                    ("<day-of-month> (ordinal)\1052\1072\1081", -4.382026634673881),
                                    ("\1089\1077\1075\1086\1076\1085\1103at <time-of-day>",
                                     -4.382026634673881),
                                    ("dayminute", -3.9765615265657175),
                                    ("\1063\1077\1090\1074\1077\1088\1075hh:mm",
                                     -3.9765615265657175),
                                    ("intersectyear", -3.6888794541139363),
                                    ("\1040\1087\1088\1077\1083\1100year", -4.382026634673881),
                                    ("intersect\1054\1082\1090\1103\1073\1088\1100",
                                     -4.382026634673881),
                                    ("year<time> <part-of-day>", -4.382026634673881),
                                    ("mm/ddyear", -3.283414346005772),
                                    ("\1052\1072\1088\1090year", -3.9765615265657175)],
                               n = 35}}),
       ("\1040\1087\1088\1077\1083\1100",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1087\1086\1089\1083\1077\1079\1072\1074\1090\1088\1072",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("year (grain)",
        Classifier{okData =
                     ClassData{prior = -0.2231435513142097,
                               unseen = -2.3025850929940455,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 8},
                   koData =
                     ClassData{prior = -1.6094379124341003,
                               unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("next <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.2188758248682006,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.791759469228055),
                                    ("month (grain)", -2.4849066497880004),
                                    ("year (grain)", -2.0794415416798357),
                                    ("week (grain)", -1.791759469228055),
                                    ("quarter", -2.0794415416798357), ("year", -2.0794415416798357),
                                    ("month", -2.4849066497880004),
                                    ("quarter (grain)", -2.0794415416798357)],
                               n = 8},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("one <cycle> before last",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("month (grain)", -0.6931471805599453),
                                    ("month", -0.6931471805599453)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("year (latent)",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 2}}),
       ("mm/dd/yyyy",
        Classifier{okData =
                     ClassData{prior = -1.0116009116784799, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -0.45198512374305727,
                               unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7}}),
       ("<ordinal> quarter <year>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("quarteryear", -0.6931471805599453),
                                    ("ordinals (first..19th)quarter (grain)year",
                                     -0.6931471805599453)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1054\1082\1090\1103\1073\1088\1100",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("ordinal 21..99",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1063\1077\1090\1074\1077\1088\1075",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1079\1080\1084\1072",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("nth <time> of <time>",
        Classifier{okData =
                     ClassData{prior = -0.5596157879354228, unseen = -2.772588722239781,
                               likelihoods =
                                 HashMap.fromList
                                   [("daymonth", -1.6094379124341003),
                                    ("dayyear", -1.6094379124341003),
                                    ("ordinals (first..19th)\1057\1088\1077\1076\1072intersect",
                                     -1.6094379124341003),
                                    ("ordinals (first..19th)intersectyear", -1.6094379124341003)],
                               n = 4},
                   koData =
                     ClassData{prior = -0.8472978603872037, unseen = -2.639057329615259,
                               likelihoods =
                                 HashMap.fromList
                                   [("daymonth", -1.466337068793427),
                                    ("monthyear", -1.8718021769015913),
                                    ("ordinals (first..19th)\1057\1088\1077\1076\1072\1054\1082\1090\1103\1073\1088\1100",
                                     -1.466337068793427),
                                    ("ordinals (first..19th)\1052\1072\1081year",
                                     -1.8718021769015913)],
                               n = 3}}),
       ("\1042\1086\1089\1082\1088\1077\1089\1077\1085\1100\1077",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("week (grain)",
        Classifier{okData =
                     ClassData{prior = -0.12516314295400605,
                               unseen = -2.833213344056216,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 15},
                   koData =
                     ClassData{prior = -2.1400661634962708,
                               unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("<part-of-day> of <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.639057329615259,
                               likelihoods =
                                 HashMap.fromList
                                   [("hourday", -0.9555114450274363),
                                    ("nightabsorption of , after named day", -1.8718021769015913),
                                    ("night\1057\1091\1073\1073\1086\1090\1072",
                                     -1.8718021769015913),
                                    ("nightintersect by ','", -1.8718021769015913),
                                    ("nightintersect", -1.8718021769015913)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<day-of-month>(ordinal) <named-month>",
        Classifier{okData =
                     ClassData{prior = -0.19671029424605427, unseen = -4.0943445622221,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..19th)\1060\1077\1074\1088\1072\1083\1100",
                                     -2.691243082785829),
                                    ("ordinals (first..19th)\1040\1087\1088\1077\1083\1100",
                                     -3.3843902633457743),
                                    ("ordinal 21..99\1054\1082\1090\1103\1073\1088\1100",
                                     -3.3843902633457743),
                                    ("ordinal (digits)\1052\1072\1088\1090", -2.9789251552376097),
                                    ("ordinals (first..19th)\1040\1074\1075\1091\1089\1090",
                                     -3.3843902633457743),
                                    ("ordinals (first..19th)\1052\1072\1088\1090",
                                     -2.691243082785829),
                                    ("ordinal 21..99\1060\1077\1074\1088\1072\1083\1100",
                                     -2.691243082785829),
                                    ("month", -0.8994836135577737),
                                    ("ordinal (digits)\1054\1082\1090\1103\1073\1088\1100",
                                     -3.3843902633457743),
                                    ("ordinal (digits)\1060\1077\1074\1088\1072\1083\1100",
                                     -1.9980959022258835),
                                    ("ordinal 21..99\1052\1072\1081", -3.3843902633457743)],
                               n = 23},
                   koData =
                     ClassData{prior = -1.7227665977411035,
                               unseen = -3.1780538303479458,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..19th)\1060\1077\1074\1088\1072\1083\1100",
                                     -1.749199854809259),
                                    ("ordinals (first..19th)\1054\1082\1090\1103\1073\1088\1100",
                                     -2.4423470353692043),
                                    ("month", -1.3437347467010947),
                                    ("ordinals (first..19th)\1052\1072\1081", -2.4423470353692043)],
                               n = 5}}),
       ("\1048\1102\1083\1100",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1053\1086\1103\1073\1088\1100",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1040\1074\1075\1091\1089\1090",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1057\1077\1085\1090\1103\1073\1088\1100",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer 2",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 9},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("afternoon",
        Classifier{okData =
                     ClassData{prior = -0.587786664902119, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -0.8109302162163288, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4}}),
       ("minute (grain)",
        Classifier{okData =
                     ClassData{prior = -0.2876820724517809,
                               unseen = -2.3978952727983707,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 9},
                   koData =
                     ClassData{prior = -1.3862943611198906,
                               unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3}}),
       ("night",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1079\1072\1074\1090\1088\1072",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("time-of-day (latent)",
        Classifier{okData =
                     ClassData{prior = -0.42608439531090014,
                               unseen = -3.6109179126442243,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.1823215567939546),
                                    ("integer (3..19)", -2.1972245773362196)],
                               n = 32},
                   koData =
                     ClassData{prior = -1.0586069540544105,
                               unseen = -3.0910424533583156,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.4795730802618862),
                                    ("integer (3..19)", -1.9459101490553135),
                                    ("integer 1", -2.3513752571634776),
                                    ("integer 2", -1.9459101490553135)],
                               n = 17}}),
       ("\1087\1086\1089\1083\1077\1087\1086\1089\1083\1077\1079\1072\1074\1090\1088\1072",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("year",
        Classifier{okData =
                     ClassData{prior = -0.3101549283038396,
                               unseen = -3.1780538303479458,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 22},
                   koData =
                     ClassData{prior = -1.3217558399823195,
                               unseen = -2.3025850929940455,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 8}}),
       ("<integer> <unit-of-duration>",
        Classifier{okData =
                     ClassData{prior = -1.252762968495368, unseen = -4.304065093204169,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.498699971920336),
                                    ("integer 2week (grain)", -3.597312260588446),
                                    ("integer (numeric)day (grain)", -2.681021528714291),
                                    ("integer 1hour (grain)", -3.597312260588446),
                                    ("second", -3.597312260588446),
                                    ("integer 2hour (grain)", -3.597312260588446),
                                    ("integer (numeric)second (grain) ", -3.597312260588446),
                                    ("integer (numeric)year (grain)", -3.597312260588446),
                                    ("day", -2.681021528714291), ("year", -3.1918471524802814),
                                    ("integer (3..19)week (grain)", -3.597312260588446),
                                    ("integer (numeric)week (grain)", -2.9041650800285006),
                                    ("hour", -2.681021528714291), ("month", -3.597312260588446),
                                    ("integer (numeric)minute (grain)", -2.498699971920336),
                                    ("integer (3..19)month (grain)", -3.597312260588446),
                                    ("minute", -2.498699971920336),
                                    ("integer (numeric)hour (grain)", -3.1918471524802814),
                                    ("integer 2year (grain)", -3.597312260588446)],
                               n = 22},
                   koData =
                     ClassData{prior = -0.3364722366212129, unseen = -4.941642422609305,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -3.3250360206965914),
                                    ("integer 2week (grain)", -4.241326752570746),
                                    ("integer (numeric)day (grain)", -3.548179572010801),
                                    ("integer (3..19)day (grain)", -4.241326752570746),
                                    ("integer 2minute (grain)", -4.241326752570746),
                                    ("second", -3.3250360206965914),
                                    ("integer 2month (grain)", -4.241326752570746),
                                    ("integer (3..19)second (grain) ", -4.241326752570746),
                                    ("integer (numeric)second (grain) ", -3.835861644462582),
                                    ("integer (numeric)year (grain)", -3.835861644462582),
                                    ("integer (3..19)year (grain)", -4.241326752570746),
                                    ("day", -3.1427144639026365), ("year", -3.3250360206965914),
                                    ("integer (3..19)week (grain)", -4.241326752570746),
                                    ("integer 2day (grain)", -4.241326752570746),
                                    ("integer (numeric)week (grain)", -3.835861644462582),
                                    ("integer (3..19)minute (grain)", -4.241326752570746),
                                    ("hour", -1.602269422955488), ("month", -3.3250360206965914),
                                    ("integer (numeric)minute (grain)", -3.1427144639026365),
                                    ("integer 2second (grain) ", -4.241326752570746),
                                    ("integer (3..19)month (grain)", -4.241326752570746),
                                    ("integer (numeric)month (grain)", -3.835861644462582),
                                    ("integer (3..19)hour (grain)", -3.835861644462582),
                                    ("minute", -2.8550323914508557),
                                    ("integer (numeric)hour (grain)", -1.6763773951092098),
                                    ("integer 2year (grain)", -4.241326752570746)],
                               n = 55}}),
       ("ordinals (first..19th)",
        Classifier{okData =
                     ClassData{prior = -0.5389965007326869, unseen = -2.772588722239781,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 14},
                   koData =
                     ClassData{prior = -0.8754687373538999,
                               unseen = -2.4849066497880004,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 10}}),
       ("\1057\1091\1073\1073\1086\1090\1072",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("a <unit-of-duration>",
        Classifier{okData =
                     ClassData{prior = -3.109060958860994, unseen = -3.295836866004329,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.8718021769015913),
                                    ("hour (grain)", -2.5649493574615367),
                                    ("second", -2.5649493574615367),
                                    ("week (grain)", -1.8718021769015913),
                                    ("second (grain) ", -2.5649493574615367),
                                    ("hour", -2.5649493574615367)],
                               n = 5},
                   koData =
                     ClassData{prior = -4.567003683318832e-2,
                               unseen = -5.442417710521793,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.7300291078209855),
                                    ("month (grain)", -2.873129951461659),
                                    ("hour (grain)", -1.911718784307034),
                                    ("year (grain)", -3.040184036124825),
                                    ("second", -3.6463198396951406),
                                    ("week (grain)", -2.7300291078209855),
                                    ("day", -2.7300291078209855), ("quarter", -3.3586377672433594),
                                    ("minute (grain)", -2.873129951461659),
                                    ("year", -3.040184036124825),
                                    ("second (grain) ", -3.6463198396951406),
                                    ("hour", -1.911718784307034), ("month", -2.873129951461659),
                                    ("quarter (grain)", -3.3586377672433594),
                                    ("minute", -2.873129951461659),
                                    ("day (grain)", -2.7300291078209855)],
                               n = 107}}),
       ("dd.(mm.)? - dd.mm.(yy[yy]?)? (interval)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.639057329615259,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 12},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("hh:mm",
        Classifier{okData =
                     ClassData{prior = -4.8790164169432056e-2,
                               unseen = -3.0910424533583156,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 20},
                   koData =
                     ClassData{prior = -3.044522437723423, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("intersect by ','",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.02535169073515,
                               likelihoods =
                                 HashMap.fromList
                                   [("hourday", -3.3141860046725258),
                                    ("dayhour", -2.908720896564361),
                                    ("\1055\1086\1085\1077\1076\1077\1083\1100\1085\1080\1082<day-of-month> (non ordinal) <named-month>",
                                     -2.908720896564361),
                                    ("\1055\1103\1090\1085\1080\1094\1072mm/dd",
                                     -3.3141860046725258),
                                    ("\1057\1088\1077\1076\1072<day-of-month> (non ordinal) <named-month>",
                                     -3.3141860046725258),
                                    ("\1057\1088\1077\1076\1072<day-of-month>(ordinal) <named-month>",
                                     -3.3141860046725258),
                                    ("\1055\1103\1090\1085\1080\1094\1072intersect",
                                     -2.3978952727983707),
                                    ("dayday", -1.2992829841302609),
                                    ("intersect<day-of-month> (non ordinal) <named-month>",
                                     -2.908720896564361),
                                    ("\1057\1088\1077\1076\1072intersect", -3.3141860046725258),
                                    ("\1057\1091\1073\1073\1086\1090\1072<day-of-month> (non ordinal) <named-month>",
                                     -3.3141860046725258),
                                    ("minuteday", -2.908720896564361),
                                    ("\1055\1103\1090\1085\1080\1094\1072mm/dd/yyyy",
                                     -3.3141860046725258),
                                    ("\1042\1086\1089\1082\1088\1077\1089\1077\1085\1100\1077<day-of-month> (non ordinal) <named-month>",
                                     -3.3141860046725258),
                                    ("<part-of-day> of <time><day-of-month> (non ordinal) <named-month>",
                                     -3.3141860046725258),
                                    ("\1055\1103\1090\1085\1080\1094\1072<day-of-month> (non ordinal) <named-month>",
                                     -2.908720896564361),
                                    ("\1057\1088\1077\1076\1072<day-of-month> (ordinal)",
                                     -3.3141860046725258)],
                               n = 19},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.890371757896165,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("second (grain) ",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1042\1090\1086\1088\1085\1080\1082",
        Classifier{okData =
                     ClassData{prior = -0.15415067982725836,
                               unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6},
                   koData =
                     ClassData{prior = -1.9459101490553135,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("\1055\1103\1090\1085\1080\1094\1072",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<duration> ago",
        Classifier{okData =
                     ClassData{prior = -0.5306282510621704, unseen = -3.295836866004329,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.466337068793427), ("day", -1.8718021769015913),
                                    ("year", -2.5649493574615367),
                                    ("<integer> <unit-of-duration>", -1.0608719606852628),
                                    ("a <unit-of-duration>", -2.159484249353372),
                                    ("month", -2.5649493574615367)],
                               n = 10},
                   koData =
                     ClassData{prior = -0.8873031950009028, unseen = -3.044522437723423,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.8971199848858813), ("day", -1.6094379124341003),
                                    ("year", -2.3025850929940455),
                                    ("a <unit-of-duration>", -0.916290731874155),
                                    ("month", -2.3025850929940455)],
                               n = 7}}),
       ("last <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -0.6931471805599453),
                                    ("\1042\1090\1086\1088\1085\1080\1082", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<day-of-month> (ordinal)",
        Classifier{okData =
                     ClassData{prior = -0.44468582126144557,
                               unseen = -3.367295829986474,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinal 21..99", -1.540445040947149),
                                    ("ordinals (first..19th)", -0.9343092373768334),
                                    ("ordinal (digits)", -0.9343092373768334)],
                               n = 25},
                   koData =
                     ClassData{prior = -1.024504316514388, unseen = -2.890371757896165,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..19th)", -0.12516314295400605)],
                               n = 14}}),
       ("noon",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("until <time-of-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.332204510175204,
                               likelihoods =
                                 HashMap.fromList
                                   [("<time> <part-of-day>", -2.1972245773362196),
                                    ("\1050\1086\1085\1077\1094 \1084\1077\1089\1103\1094\1072",
                                     -2.6026896854443837),
                                    ("<time-of-day>  o'clock", -1.9095425048844386),
                                    ("time-of-day (latent)", -1.9095425048844386),
                                    ("hour", -0.9932517730102834), ("month", -2.6026896854443837),
                                    ("midnight|EOD|end of day", -2.6026896854443837)],
                               n = 10},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1060\1077\1074\1088\1072\1083\1100",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.0910424533583156,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 20},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("evening",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("decimal number",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -3.6109179126442243,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 35}}),
       ("midnight|EOD|end of day",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("last <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("month (grain)", -0.6931471805599453),
                                    ("month", -0.6931471805599453)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("next n <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.912023005428146,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.793208009442517),
                                    ("integer (numeric)day (grain)", -3.1986731175506815),
                                    ("integer (3..19)day (grain)", -3.1986731175506815),
                                    ("second", -2.793208009442517),
                                    ("integer (3..19)second (grain) ", -3.1986731175506815),
                                    ("integer (numeric)second (grain) ", -3.1986731175506815),
                                    ("integer (numeric)year (grain)", -3.1986731175506815),
                                    ("integer (3..19)year (grain)", -3.1986731175506815),
                                    ("day", -2.793208009442517), ("year", -2.793208009442517),
                                    ("integer (3..19)week (grain)", -3.1986731175506815),
                                    ("integer (numeric)week (grain)", -3.1986731175506815),
                                    ("integer (3..19)minute (grain)", -3.1986731175506815),
                                    ("hour", -2.793208009442517), ("month", -2.793208009442517),
                                    ("integer (numeric)minute (grain)", -3.1986731175506815),
                                    ("integer (3..19)month (grain)", -3.1986731175506815),
                                    ("integer (numeric)month (grain)", -3.1986731175506815),
                                    ("integer (3..19)hour (grain)", -3.1986731175506815),
                                    ("minute", -2.793208009442517),
                                    ("integer (numeric)hour (grain)", -3.1986731175506815)],
                               n = 14},
                   koData =
                     ClassData{prior = -infinity, unseen = -3.0910424533583156,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("in <duration>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.713572066704308,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.5902671654458267), ("second", -2.5902671654458267),
                                    ("day", -2.995732273553991), ("year", -2.995732273553991),
                                    ("<integer> <unit-of-duration>", -1.0498221244986778),
                                    ("a <unit-of-duration>", -2.3025850929940455),
                                    ("hour", -1.8971199848858813), ("minute", -1.8971199848858813)],
                               n = 16},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<datetime> - <datetime> (interval)",
        Classifier{okData =
                     ClassData{prior = -0.45198512374305727,
                               unseen = -3.2188758248682006,
                               likelihoods =
                                 HashMap.fromList
                                   [("minuteminute", -1.791759469228055),
                                    ("hh:mmhh:mm", -1.791759469228055),
                                    ("dayday", -1.5686159179138452),
                                    ("<day-of-month> (non ordinal) <named-month><day-of-month> (non ordinal) <named-month>",
                                     -2.0794415416798357),
                                    ("mm/ddmm/dd", -2.0794415416798357)],
                               n = 7},
                   koData =
                     ClassData{prior = -1.0116009116784799,
                               unseen = -2.9444389791664407,
                               likelihoods =
                                 HashMap.fromList
                                   [("monthday", -1.791759469228055),
                                    ("mm/ddmm/dd/yyyy", -2.1972245773362196),
                                    ("\1048\1102\1083\1100<day-of-month> (non ordinal) <named-month>",
                                     -2.1972245773362196),
                                    ("\1040\1074\1075\1091\1089\1090<day-of-month> (non ordinal) <named-month>",
                                     -2.1972245773362196),
                                    ("dayday", -1.791759469228055),
                                    ("mm/ddintersect", -2.1972245773362196)],
                               n = 4}}),
       ("\1089\1077\1075\1086\1076\1085\1103",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time-of-day> - <time-of-day> (interval)",
        Classifier{okData =
                     ClassData{prior = -0.15415067982725836,
                               unseen = -2.833213344056216,
                               likelihoods =
                                 HashMap.fromList
                                   [("hh:mmtime-of-day (latent)", -1.6739764335716716),
                                    ("minuteminute", -1.1631508098056809),
                                    ("hh:mmhh:mm", -1.1631508098056809),
                                    ("minutehour", -1.6739764335716716)],
                               n = 6},
                   koData =
                     ClassData{prior = -1.9459101490553135,
                               unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("hh:mmtime-of-day (latent)", -1.0986122886681098),
                                    ("minutehour", -1.0986122886681098)],
                               n = 1}}),
       ("last n <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.7612001156935624,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.639057329615259),
                                    ("integer 2week (grain)", -3.044522437723423),
                                    ("integer (numeric)day (grain)", -3.044522437723423),
                                    ("integer 2minute (grain)", -3.044522437723423),
                                    ("second", -2.639057329615259),
                                    ("integer 2month (grain)", -3.044522437723423),
                                    ("integer (numeric)second (grain) ", -3.044522437723423),
                                    ("integer (numeric)year (grain)", -3.044522437723423),
                                    ("day", -2.639057329615259), ("year", -2.639057329615259),
                                    ("integer 2day (grain)", -3.044522437723423),
                                    ("integer (numeric)week (grain)", -3.044522437723423),
                                    ("month", -2.639057329615259),
                                    ("integer (numeric)minute (grain)", -3.044522437723423),
                                    ("integer 2second (grain) ", -3.044522437723423),
                                    ("integer (numeric)month (grain)", -3.044522437723423),
                                    ("minute", -2.639057329615259),
                                    ("integer 2year (grain)", -3.044522437723423)],
                               n = 12},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.9444389791664407,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<day-of-month> (non ordinal) <named-month>",
        Classifier{okData =
                     ClassData{prior = -9.53101798043249e-2,
                               unseen = -3.871201010907891,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)\1052\1072\1088\1090", -2.463853240590168),
                                    ("integer (numeric)\1048\1102\1083\1100", -2.2407096892759584),
                                    ("integer (numeric)\1057\1077\1085\1090\1103\1073\1088\1100",
                                     -3.1570004211501135),
                                    ("integer (numeric)\1040\1074\1075\1091\1089\1090",
                                     -2.2407096892759584),
                                    ("integer (numeric)\1040\1087\1088\1077\1083\1100",
                                     -3.1570004211501135),
                                    ("integer (numeric)\1060\1077\1074\1088\1072\1083\1100",
                                     -1.7707060600302227),
                                    ("month", -0.8056251639866356)],
                               n = 20},
                   koData =
                     ClassData{prior = -2.3978952727983707,
                               unseen = -2.4849066497880004,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)\1048\1102\1083\1100", -1.2992829841302609),
                                    ("month", -1.2992829841302609)],
                               n = 2}}),
       ("this|next <day-of-week>",
        Classifier{okData =
                     ClassData{prior = -0.40546510810816444,
                               unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1055\1086\1085\1077\1076\1077\1083\1100\1085\1080\1082",
                                     -1.3862943611198906),
                                    ("day", -0.9808292530117262),
                                    ("\1042\1090\1086\1088\1085\1080\1082", -1.3862943611198906)],
                               n = 2},
                   koData =
                     ClassData{prior = -1.0986122886681098,
                               unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1057\1088\1077\1076\1072", -1.0986122886681098),
                                    ("day", -1.0986122886681098)],
                               n = 1}}),
       ("ordinal (digits)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.4849066497880004,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 10},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("quarter (grain)",
        Classifier{okData =
                     ClassData{prior = -0.3364722366212129,
                               unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -1.252762968495368, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("last <cycle> of <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("weekmonth", -0.8472978603872037),
                                    ("week (grain)\1057\1077\1085\1090\1103\1073\1088\1100",
                                     -1.252762968495368),
                                    ("week (grain)intersect", -1.252762968495368)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1052\1072\1088\1090",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3025850929940455,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 8},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<day-of-month>(ordinal) <named-month> year",
        Classifier{okData =
                     ClassData{prior = -0.25131442828090605,
                               unseen = -3.1780538303479458,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..19th)\1040\1087\1088\1077\1083\1100",
                                     -2.4423470353692043),
                                    ("ordinal 21..99\1054\1082\1090\1103\1073\1088\1100",
                                     -2.4423470353692043),
                                    ("ordinal (digits)\1052\1072\1088\1090", -2.4423470353692043),
                                    ("ordinals (first..19th)\1052\1072\1088\1090",
                                     -2.03688192726104),
                                    ("month", -1.0560526742493137),
                                    ("ordinal (digits)\1054\1082\1090\1103\1073\1088\1100",
                                     -2.4423470353692043),
                                    ("ordinal 21..99\1052\1072\1081", -2.4423470353692043)],
                               n = 7},
                   koData =
                     ClassData{prior = -1.5040773967762742, unseen = -2.639057329615259,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..19th)\1054\1082\1090\1103\1073\1088\1100",
                                     -1.8718021769015913),
                                    ("month", -1.466337068793427),
                                    ("ordinals (first..19th)\1052\1072\1081", -1.8718021769015913)],
                               n = 2}}),
       ("\1056\1086\1078\1076\1077\1089\1090\1074\1086 \1061\1088\1080\1089\1090\1086\1074\1086",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("morning",
        Classifier{okData =
                     ClassData{prior = -0.2876820724517809,
                               unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -1.3862943611198906,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("week-end",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("after <time-of-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.772588722239781,
                               likelihoods =
                                 HashMap.fromList
                                   [("<time-of-day>  o'clock", -1.3217558399823195),
                                    ("time-of-day (latent)", -1.3217558399823195),
                                    ("hour", -0.7621400520468967)],
                               n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("day (grain)",
        Classifier{okData =
                     ClassData{prior = -0.5596157879354228,
                               unseen = -2.3025850929940455,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 8},
                   koData =
                     ClassData{prior = -0.8472978603872037,
                               unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6}}),
       ("\1052\1072\1081",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<month> dd-dd (interval)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1048\1102\1083\1100", -0.6931471805599453),
                                    ("month", -0.6931471805599453)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("composite <duration>",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("hourminute", -0.6931471805599453),
                                    ("integer (numeric)hour (grain)<integer> <unit-of-duration>",
                                     -0.6931471805599453)],
                               n = 1}}),
       ("<hour-of-day> <integer> (as relative minutes)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("hour", -0.6931471805599453),
                                    ("<time-of-day>  o'clockinteger (numeric)",
                                     -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("this <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("hour", -0.6931471805599453),
                                    ("week-end", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("within <duration>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -0.6931471805599453),
                                    ("<integer> <unit-of-duration>", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}})]