-- Copyright (c) 2016-present, Facebook, Inc.
-- All rights reserved.
--
-- This source code is licensed under the BSD-style license found in the
-- LICENSE file in the root directory of this source tree. An additional grant
-- of patent rights can be found in the PATENTS file in the same directory.

-----------------------------------------------------------------
-- Auto-generated by regenClassifiers
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
--  @generated
-----------------------------------------------------------------
{-# LANGUAGE OverloadedStrings #-}
module Duckling.Ranking.Classifiers.SV (classifiers) where
import Prelude
import Duckling.Ranking.Types
import qualified Data.HashMap.Strict as HashMap
import Data.String

classifiers :: Classifiers
classifiers
  = HashMap.fromList
      [("<time> timezone",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.044522437723423,
                               likelihoods =
                                 HashMap.fromList
                                   [("at <time-of-day>", -1.2039728043259361),
                                    ("hh:mm", -1.6094379124341003), ("hour", -1.6094379124341003),
                                    ("minute", -1.2039728043259361)],
                               n = 8},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer (numeric)",
        Classifier{okData =
                     ClassData{prior = -0.7600866632350547, unseen = -4.882801922586371,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 130},
                   koData =
                     ClassData{prior = -0.630408839926522, unseen = -5.0106352940962555,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 148}}),
       ("the day before yesterday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("lunch",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("integer (20..90)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time> <part-of-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.639057329615259,
                               likelihoods =
                                 HashMap.fromList
                                   [("dayhour", -0.9555114450274363),
                                    ("tomorrowevening", -1.8718021769015913),
                                    ("named-daymorning", -1.8718021769015913),
                                    ("tomorrowlunch", -1.8718021769015913),
                                    ("yesterdayevening", -1.8718021769015913)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("couple, a pair",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("dd/mm",
        Classifier{okData =
                     ClassData{prior = -0.2231435513142097,
                               unseen = -2.3025850929940455,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 8},
                   koData =
                     ClassData{prior = -1.6094379124341003,
                               unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("today",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("at <time-of-day>",
        Classifier{okData =
                     ClassData{prior = -0.2607262624632527, unseen = -4.624972813284271,
                               likelihoods =
                                 HashMap.fromList
                                   [("<time> timezone", -3.5165082281731497),
                                    ("time-of-day (latent)", -1.2139231351791042),
                                    ("relative minutes after|past <integer> (hour-of-day)",
                                     -3.5165082281731497),
                                    ("hh:mm", -2.0501711593797225),
                                    ("<time-of-day> sharp", -3.5165082281731497),
                                    ("hour", -1.149384614041533), ("minute", -1.7819071727850433)],
                               n = 47},
                   koData =
                     ClassData{prior = -1.4718165345580525, unseen = -3.58351893845611,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -0.8472978603872037),
                                    ("hour", -0.8472978603872037)],
                               n = 14}}),
       ("absorption of , after named day",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.9444389791664407,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -0.6931471805599453),
                                    ("named-day", -0.6931471805599453)],
                               n = 8},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("tonight",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("on <date>",
        Classifier{okData =
                     ClassData{prior = -0.48285177172358457,
                               unseen = -4.276666119016055,
                               likelihoods =
                                 HashMap.fromList
                                   [("on <date>", -3.56953269648137),
                                    ("the <day-of-month> (non ordinal)", -3.164067588373206),
                                    ("<day-of-month>(ordinal) <named-month>", -2.316769727986002),
                                    ("day", -0.8953840470548413),
                                    ("the <day-of-month> (ordinal)", -3.56953269648137),
                                    ("afternoon", -3.56953269648137),
                                    ("named-day", -1.9600947840472698),
                                    ("<day-of-month> (ordinal)", -2.065455299705096),
                                    ("hour", -3.56953269648137),
                                    ("<day-of-month> (non ordinal) <named-month>",
                                     -3.56953269648137)],
                               n = 29},
                   koData =
                     ClassData{prior = -0.9597758438138939, unseen = -3.912023005428146,
                               likelihoods =
                                 HashMap.fromList
                                   [("on <date>", -2.2823823856765264),
                                    ("year (latent)", -1.8123787564307907),
                                    ("time-of-day (latent)", -1.8123787564307907),
                                    ("year", -1.589235205116581), ("hour", -1.589235205116581)],
                               n = 18}}),
       ("integer (0..19)",
        Classifier{okData =
                     ClassData{prior = -0.2578291093020998, unseen = -3.58351893845611,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 34},
                   koData =
                     ClassData{prior = -1.4816045409242156,
                               unseen = -2.4849066497880004,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 10}}),
       ("between <time-of-day> and <time-of-day> (interval)",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("minuteminute", -0.9808292530117262),
                                    ("hh:mmhh:mm", -0.9808292530117262)],
                               n = 2},
                   koData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("hh:mmtime-of-day (latent)", -0.9808292530117262),
                                    ("minutehour", -0.9808292530117262)],
                               n = 2}}),
       ("between <datetime> and <datetime> (interval)",
        Classifier{okData =
                     ClassData{prior = -0.916290731874155, unseen = -2.3025850929940455,
                               likelihoods =
                                 HashMap.fromList
                                   [("minuteminute", -1.0986122886681098),
                                    ("hh:mmhh:mm", -1.0986122886681098)],
                               n = 2},
                   koData =
                     ClassData{prior = -0.5108256237659907,
                               unseen = -2.4849066497880004,
                               likelihoods =
                                 HashMap.fromList
                                   [("hh:mmtime-of-day (latent)", -1.2992829841302609),
                                    ("minuteminute", -1.7047480922384253),
                                    ("minutehour", -1.2992829841302609),
                                    ("hh:mmintersect", -1.7047480922384253)],
                               n = 3}}),
       ("month (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 9},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<integer> more <unit-of-duration>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)minute (grain)", -1.252762968495368),
                                    ("integer (0..19)minute (grain)", -1.252762968495368),
                                    ("minute", -0.8472978603872037)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time-of-day> o'clock",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("hour (grain)",
        Classifier{okData =
                     ClassData{prior = -0.11778303565638351,
                               unseen = -2.3025850929940455,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 8},
                   koData =
                     ClassData{prior = -2.1972245773362196,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("<ordinal> quarter",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinal (digits)quarter (grain)", -1.252762968495368),
                                    ("ordinals (first..twentieth,thirtieth,...)quarter (grain)",
                                     -1.252762968495368),
                                    ("quarter", -0.8472978603872037)],
                               n = 2},
                   koData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinal (digits)quarter (grain)", -1.252762968495368),
                                    ("ordinals (first..twentieth,thirtieth,...)quarter (grain)",
                                     -1.252762968495368),
                                    ("quarter", -0.8472978603872037)],
                               n = 2}}),
       ("Last year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("intersect",
        Classifier{okData =
                     ClassData{prior = -0.4434925036974037, unseen = -5.8111409929767,
                               likelihoods =
                                 HashMap.fromList
                                   [("<datetime> - <datetime> (interval)on <date>",
                                     -4.0163830207523885),
                                    ("<time-of-day> - <time-of-day> (interval)on <date>",
                                     -4.0163830207523885),
                                    ("hourday", -5.1149953094204985),
                                    ("dayhour", -2.863703510814003),
                                    ("daymonth", -2.9749291459242277),
                                    ("monthyear", -3.100092288878234),
                                    ("intersecthh:mm", -5.1149953094204985),
                                    ("named-daylast <cycle>", -5.1149953094204985),
                                    ("the <day-of-month> (ordinal)named-month",
                                     -3.8622323409251305),
                                    ("intersect by \"of\", \"from\", \"'s\"year",
                                     -4.709530201312334),
                                    ("last <day-of-week> of <time>year", -5.1149953094204985),
                                    ("todayat <time-of-day>", -4.709530201312334),
                                    ("dayday", -3.243193132518907),
                                    ("dd/mmat <time-of-day>", -4.198704577546343),
                                    ("intersect by \",\"hh:mm", -4.198704577546343),
                                    ("dayyear", -3.3232358401924436),
                                    ("named-daythis <time>", -4.0163830207523885),
                                    ("tomorrow<time-of-day> sharp", -4.709530201312334),
                                    ("<day-of-month>(ordinal) <named-month>year",
                                     -4.709530201312334),
                                    ("named-day<time> timezone", -4.421848128860553),
                                    ("named-monthyear", -3.100092288878234),
                                    ("absorption of , after named day<named-month> <day-of-month> (non ordinal)",
                                     -4.0163830207523885),
                                    ("on <date>named-month", -3.8622323409251305),
                                    ("tomorrowuntil <time-of-day>", -4.709530201312334),
                                    ("absorption of , after named day<day-of-month> (non ordinal) <named-month>",
                                     -4.421848128860553),
                                    ("after <time-of-day>at <time-of-day>", -4.709530201312334),
                                    ("intersect by \",\"<day-of-month> (non ordinal) <named-month>",
                                     -4.709530201312334),
                                    ("named-day<day-of-month> (non ordinal) <named-month>",
                                     -5.1149953094204985),
                                    ("named-day<named-month> <day-of-month> (non ordinal)",
                                     -5.1149953094204985),
                                    ("named-dayfrom <datetime> - <datetime> (interval)",
                                     -4.709530201312334),
                                    ("named-daynext <cycle>", -5.1149953094204985),
                                    ("named-dayfrom <time-of-day> - <time-of-day> (interval)",
                                     -4.709530201312334),
                                    ("tomorrowafter <time-of-day>", -4.709530201312334),
                                    ("from <time-of-day> - <time-of-day> (interval)on <date>",
                                     -4.198704577546343),
                                    ("dayminute", -2.763620052257021),
                                    ("from <datetime> - <datetime> (interval)on <date>",
                                     -4.421848128860553),
                                    ("<ordinal> <cycle> of <time>year", -4.709530201312334),
                                    ("minuteday", -2.512305623976115),
                                    ("absorption of , after named dayintersect",
                                     -5.1149953094204985),
                                    ("named-daybetween <time-of-day> and <time-of-day> (interval)",
                                     -5.1149953094204985),
                                    ("named-dayon <date>", -5.1149953094204985),
                                    ("named-dayat <time-of-day>", -4.709530201312334),
                                    ("yearhh:mm", -5.1149953094204985),
                                    ("named-daybetween <datetime> and <datetime> (interval)",
                                     -5.1149953094204985),
                                    ("absorption of , after named dayintersect by \",\"",
                                     -4.709530201312334),
                                    ("dd/mmyear", -4.709530201312334),
                                    ("at <time-of-day>on <date>", -5.1149953094204985),
                                    ("between <time-of-day> and <time-of-day> (interval)on <date>",
                                     -5.1149953094204985),
                                    ("between <datetime> and <datetime> (interval)on <date>",
                                     -5.1149953094204985),
                                    ("dayweek", -3.8622323409251305),
                                    ("weekyear", -4.198704577546343),
                                    ("hh:mmtomorrow", -4.421848128860553),
                                    ("tomorrowat <time-of-day>", -3.8622323409251305),
                                    ("named-daythis <cycle>", -4.421848128860553),
                                    ("at <time-of-day>tomorrow", -4.709530201312334),
                                    ("last <cycle> of <time>year", -4.198704577546343),
                                    ("<day-of-month> (non ordinal) <named-month>year",
                                     -4.709530201312334),
                                    ("yearminute", -5.1149953094204985)],
                               n = 129},
                   koData =
                     ClassData{prior = -1.0266387890430204, unseen = -5.393627546352362,
                               likelihoods =
                                 HashMap.fromList
                                   [("named-daynamed-month", -4.695924549256556),
                                    ("dayhour", -3.1918471524802814),
                                    ("daymonth", -2.130975191795019),
                                    ("monthday", -3.7796338173824005),
                                    ("monthyear", -3.7796338173824005),
                                    ("intersect by \"of\", \"from\", \"'s\"year",
                                     -3.597312260588446),
                                    ("hourmonth", -4.290459441148391),
                                    ("named-dayhh:mm", -4.695924549256556),
                                    ("dd/mmat <time-of-day>", -3.7796338173824005),
                                    ("intersectnamed-month", -4.290459441148391),
                                    ("dayyear", -3.3096301881366648),
                                    ("named-daythis <time>", -2.750014400201242),
                                    ("year<hour-of-day> <integer> (as relative minutes)",
                                     -4.290459441148391),
                                    ("minutemonth", -4.290459441148391),
                                    ("named-monthyear", -3.7796338173824005),
                                    ("on <date>named-month", -4.290459441148391),
                                    ("absorption of , after named daynamed-month",
                                     -3.597312260588446),
                                    ("named-dayfrom <datetime> - <datetime> (interval)",
                                     -4.290459441148391),
                                    ("named-dayintersect", -4.290459441148391),
                                    ("<hour-of-day> <integer> (as relative minutes)named-month",
                                     -4.290459441148391),
                                    ("named-dayfrom <time-of-day> - <time-of-day> (interval)",
                                     -4.695924549256556),
                                    ("yearmonth", -4.695924549256556),
                                    ("until <time-of-day>on <date>", -4.695924549256556),
                                    ("dayminute", -3.3096301881366648),
                                    ("minuteday", -3.1918471524802814),
                                    ("named-daybetween <time-of-day> and <time-of-day> (interval)",
                                     -4.695924549256556),
                                    ("named-dayon <date>", -4.290459441148391),
                                    ("named-dayat <time-of-day>", -3.7796338173824005),
                                    ("hh:mmon <date>", -3.3096301881366648),
                                    ("named-daybetween <datetime> and <datetime> (interval)",
                                     -4.695924549256556),
                                    ("named-month<day-of-month> (non ordinal) <named-month>",
                                     -3.7796338173824005),
                                    ("<named-month> <day-of-month> (non ordinal)named-month",
                                     -3.7796338173824005),
                                    ("<hour-of-day> <integer> (as relative minutes)year",
                                     -4.290459441148391),
                                    ("minuteyear", -4.290459441148391),
                                    ("yearminute", -4.290459441148391)],
                               n = 72}}),
       ("<ordinal> <cycle> of <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.890371757896165,
                               likelihoods =
                                 HashMap.fromList
                                   [("daymonth", -1.7346010553881064),
                                    ("ordinals (first..twentieth,thirtieth,...)day (grain)named-month",
                                     -1.7346010553881064),
                                    ("ordinals (first..twentieth,thirtieth,...)week (grain)intersect",
                                     -1.7346010553881064),
                                    ("weekmonth", -1.2237754316221157),
                                    ("ordinals (first..twentieth,thirtieth,...)week (grain)named-month",
                                     -1.7346010553881064)],
                               n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("season",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("year (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.5649493574615367,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 11},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("from <datetime> - <datetime> (interval)",
        Classifier{okData =
                     ClassData{prior = -1.0296194171811581,
                               unseen = -3.0910424533583156,
                               likelihoods =
                                 HashMap.fromList
                                   [("minuteminute", -1.4350845252893227),
                                    ("time-of-day (latent)time-of-day (latent)",
                                     -2.3513752571634776),
                                    ("hh:mmhh:mm", -1.4350845252893227),
                                    ("hourhour", -2.3513752571634776)],
                               n = 5},
                   koData =
                     ClassData{prior = -0.4418327522790392,
                               unseen = -3.4011973816621555,
                               likelihoods =
                                 HashMap.fromList
                                   [("yearhour", -2.6741486494265287),
                                    ("hh:mmtime-of-day (latent)", -1.7578579175523736),
                                    ("minuteminute", -1.9810014688665833),
                                    ("yearyear", -2.6741486494265287),
                                    ("year (latent)year (latent)", -2.6741486494265287),
                                    ("minutehour", -1.7578579175523736),
                                    ("hh:mmintersect", -1.9810014688665833),
                                    ("year (latent)time-of-day (latent)", -2.6741486494265287)],
                               n = 9}}),
       ("next <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.044522437723423,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.6094379124341003),
                                    ("month (grain)", -2.3025850929940455),
                                    ("year (grain)", -2.3025850929940455),
                                    ("week (grain)", -1.6094379124341003),
                                    ("quarter", -2.3025850929940455), ("year", -2.3025850929940455),
                                    ("month", -2.3025850929940455),
                                    ("quarter (grain)", -2.3025850929940455)],
                               n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("number.number hours",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("from <time-of-day> - <time-of-day> (interval)",
        Classifier{okData =
                     ClassData{prior = -0.6061358035703156,
                               unseen = -2.9444389791664407,
                               likelihoods =
                                 HashMap.fromList
                                   [("minuteminute", -1.0986122886681098),
                                    ("time-of-day (latent)time-of-day (latent)",
                                     -2.1972245773362196),
                                    ("hh:mmhh:mm", -1.0986122886681098),
                                    ("hourhour", -2.1972245773362196)],
                               n = 6},
                   koData =
                     ClassData{prior = -0.7884573603642702, unseen = -2.833213344056216,
                               likelihoods =
                                 HashMap.fromList
                                   [("hh:mmtime-of-day (latent)", -0.9808292530117262),
                                    ("minutehour", -0.9808292530117262)],
                               n = 5}}),
       ("yyyy-mm-dd",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("year (latent)",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -3.4657359027997265,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.3894647667617233),
                                    ("integer (0..19)", -1.1314021114911006)],
                               n = 29}}),
       ("dd/mm/yyyy",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("yesterday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<ordinal> quarter <year>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..twentieth,thirtieth,...)quarter (grain)year",
                                     -1.252762968495368),
                                    ("quarteryear", -0.8472978603872037),
                                    ("ordinal (digits)quarter (grain)year", -1.252762968495368)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("after lunch",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("hh:mm:ss",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("quarter to|till|before <integer> (hour-of-day)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3025850929940455,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -1.0986122886681098),
                                    ("noon", -1.5040773967762742), ("hour", -0.8109302162163288)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("nth <time> of <time>",
        Classifier{okData =
                     ClassData{prior = -0.5596157879354228, unseen = -2.995732273553991,
                               likelihoods =
                                 HashMap.fromList
                                   [("daymonth", -0.7472144018302211),
                                    ("ordinals (first..twentieth,thirtieth,...)named-dayintersect",
                                     -0.9985288301111273),
                                    ("ordinals (first..twentieth,thirtieth,...)named-daynamed-month",
                                     -1.845826690498331)],
                               n = 8},
                   koData =
                     ClassData{prior = -0.8472978603872037, unseen = -2.772588722239781,
                               likelihoods =
                                 HashMap.fromList
                                   [("daymonth", -0.7621400520468967),
                                    ("ordinals (first..twentieth,thirtieth,...)named-daynamed-month",
                                     -0.7621400520468967)],
                               n = 6}}),
       ("the <day-of-month> (non ordinal)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("named-month",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.174387269895637,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 63},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("week (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.295836866004329,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 25},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("now",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("this <part-of-day>",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("hour", -0.6931471805599453),
                                    ("morning", -0.6931471805599453)],
                               n = 1}}),
       ("<day-of-month>(ordinal) <named-month>",
        Classifier{okData =
                     ClassData{prior = -9.53101798043249e-2,
                               unseen = -3.1780538303479458,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..twentieth,thirtieth,...)named-month",
                                     -1.5260563034950494),
                                    ("ordinal (digits)named-month", -1.1895840668738362),
                                    ("month", -0.7375989431307791)],
                               n = 10},
                   koData =
                     ClassData{prior = -2.3978952727983707, unseen = -1.791759469228055,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..twentieth,thirtieth,...)named-month",
                                     -0.916290731874155),
                                    ("month", -0.916290731874155)],
                               n = 1}}),
       ("numbers prefix with -, negative or minus",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -3.2188758248682006,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 23}}),
       ("in|during the <part-of-day>",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("hour", -0.6931471805599453),
                                    ("morning", -0.6931471805599453)],
                               n = 1}}),
       ("new year's eve",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("tomorrow",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.833213344056216,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 15},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time> after next",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("named-month", -1.791759469228055),
                                    ("day", -1.0986122886681098),
                                    ("named-day", -1.0986122886681098),
                                    ("month", -1.791759469228055)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("half an hour",
        Classifier{okData =
                     ClassData{prior = -0.5108256237659907,
                               unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -0.916290731874155, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("the <day-of-month> (ordinal)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..twentieth,thirtieth,...)",
                                     -0.916290731874155),
                                    ("ordinal (digits)", -0.5108256237659907)],
                               n = 8},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("afternoon",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<duration> from now",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("second", -1.2039728043259361),
                                    ("<integer> <unit-of-duration>", -1.2039728043259361),
                                    ("a <unit-of-duration>", -1.6094379124341003),
                                    ("minute", -1.6094379124341003)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("this <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.044522437723423,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.3862943611198906),
                                    ("year (grain)", -1.8971199848858813),
                                    ("week (grain)", -1.3862943611198906),
                                    ("quarter", -2.3025850929940455), ("year", -1.8971199848858813),
                                    ("quarter (grain)", -2.3025850929940455)],
                               n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("minute (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.70805020110221,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 13},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("about <time-of-day>",
        Classifier{okData =
                     ClassData{prior = -0.5108256237659907,
                               unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 3},
                   koData =
                     ClassData{prior = -0.916290731874155, unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 2}}),
       ("time-of-day (latent)",
        Classifier{okData =
                     ClassData{prior = -0.9873866535578852, unseen = -3.713572066704308,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -5.129329438755058e-2),
                                    ("integer (0..19)", -2.995732273553991)],
                               n = 38},
                   koData =
                     ClassData{prior = -0.46608972992459924,
                               unseen = -4.204692619390966,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.23841102344499823),
                                    ("integer (0..19)", -1.550597412411167)],
                               n = 64}}),
       ("year",
        Classifier{okData =
                     ClassData{prior = -0.14842000511827333,
                               unseen = -3.295836866004329,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 25},
                   koData =
                     ClassData{prior = -1.9810014688665833, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 4}}),
       ("last <day-of-week> of <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3025850929940455,
                               likelihoods =
                                 HashMap.fromList
                                   [("named-daynamed-month", -1.0986122886681098),
                                    ("daymonth", -0.8109302162163288),
                                    ("named-dayintersect", -1.5040773967762742)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<integer> <unit-of-duration>",
        Classifier{okData =
                     ClassData{prior = -0.6231885919530349, unseen = -4.574710978503383,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.6184380424125226),
                                    ("integer (0..19)year (grain)", -3.871201010907891),
                                    ("integer (numeric)day (grain)", -2.772588722239781),
                                    ("couple, a pairhour (grain)", -3.871201010907891),
                                    ("integer (0..19)hour (grain)", -3.871201010907891),
                                    ("second", -3.1780538303479458),
                                    ("integer (numeric)second (grain)", -3.871201010907891),
                                    ("integer (numeric)year (grain)", -3.871201010907891),
                                    ("day", -2.166452918669466), ("year", -3.4657359027997265),
                                    ("integer (numeric)week (grain)", -3.1780538303479458),
                                    ("integer (0..19)month (grain)", -3.871201010907891),
                                    ("integer (0..19)second (grain)", -3.4657359027997265),
                                    ("hour", -2.772588722239781), ("month", -3.4657359027997265),
                                    ("integer (numeric)minute (grain)", -2.772588722239781),
                                    ("integer (0..19)minute (grain)", -2.9549102790337356),
                                    ("integer (numeric)month (grain)", -3.871201010907891),
                                    ("minute", -2.2617630984737906),
                                    ("integer (numeric)hour (grain)", -3.1780538303479458),
                                    ("integer (0..19)day (grain)", -2.772588722239781),
                                    ("integer (0..19)week (grain)", -3.1780538303479458)],
                               n = 37},
                   koData =
                     ClassData{prior = -0.7683706017975328, unseen = -4.465908118654584,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.662587827025453),
                                    ("integer (0..19)year (grain)", -3.355735007585398),
                                    ("integer (numeric)day (grain)", -3.068052935133617),
                                    ("integer (0..19)hour (grain)", -3.7612001156935624),
                                    ("second", -2.8449093838194073),
                                    ("integer (numeric)second (grain)", -3.355735007585398),
                                    ("integer (numeric)year (grain)", -3.068052935133617),
                                    ("day", -2.662587827025453), ("year", -2.662587827025453),
                                    ("integer (numeric)week (grain)", -3.355735007585398),
                                    ("integer (0..19)month (grain)", -3.068052935133617),
                                    ("integer (0..19)second (grain)", -3.355735007585398),
                                    ("hour", -2.8449093838194073), ("month", -2.662587827025453),
                                    ("integer (numeric)minute (grain)", -3.355735007585398),
                                    ("integer (0..19)minute (grain)", -3.355735007585398),
                                    ("integer (numeric)month (grain)", -3.355735007585398),
                                    ("minute", -2.8449093838194073),
                                    ("integer (numeric)hour (grain)", -3.068052935133617),
                                    ("integer (0..19)day (grain)", -3.355735007585398),
                                    ("integer (0..19)week (grain)", -3.068052935133617)],
                               n = 32}}),
       ("relative minutes after|past <integer> (hour-of-day)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3025850929940455,
                               likelihoods =
                                 HashMap.fromList
                                   [("hour", -0.8109302162163288),
                                    ("integer (numeric)time-of-day (latent)", -1.0986122886681098),
                                    ("integer (20..90)time-of-day (latent)", -1.5040773967762742)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("a <unit-of-duration>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.2188758248682006,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.0794415416798357),
                                    ("hour (grain)", -2.4849066497880004),
                                    ("second", -2.0794415416798357),
                                    ("week (grain)", -2.0794415416798357),
                                    ("day", -2.4849066497880004),
                                    ("minute (grain)", -2.4849066497880004),
                                    ("second (grain)", -2.0794415416798357),
                                    ("hour", -2.4849066497880004), ("minute", -2.4849066497880004),
                                    ("day (grain)", -2.4849066497880004)],
                               n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.3978952727983707,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("intersect by \",\"",
        Classifier{okData =
                     ClassData{prior = -0.1590646946296874, unseen = -4.442651256490317,
                               likelihoods =
                                 HashMap.fromList
                                   [("at <time-of-day>named-day", -3.7376696182833684),
                                    ("intersect by \",\"year", -3.7376696182833684),
                                    ("hh:mmintersect by \",\"", -3.7376696182833684),
                                    ("dayday", -2.032921526044943),
                                    ("hh:mmnamed-day", -3.7376696182833684),
                                    ("named-dayintersect by \",\"", -3.332204510175204),
                                    ("dayyear", -2.8213788864092133),
                                    ("<named-month> <day-of-month> (non ordinal)intersect",
                                     -3.7376696182833684),
                                    ("intersect by \",\"<day-of-month> (non ordinal) <named-month>",
                                     -3.332204510175204),
                                    ("<named-month> <day-of-month> (non ordinal)named-day",
                                     -3.7376696182833684),
                                    ("named-day<day-of-month> (non ordinal) <named-month>",
                                     -3.044522437723423),
                                    ("named-day<named-month> <day-of-month> (non ordinal)",
                                     -2.639057329615259),
                                    ("hh:mmintersect", -3.7376696182833684),
                                    ("intersect by \",\"intersect", -3.7376696182833684),
                                    ("named-dayintersect", -3.7376696182833684),
                                    ("at <time-of-day>intersect", -3.7376696182833684),
                                    ("dayminute", -2.639057329615259),
                                    ("intersectyear", -3.7376696182833684),
                                    ("minuteday", -2.032921526044943),
                                    ("hh:mmabsorption of , after named day", -3.7376696182833684),
                                    ("at <time-of-day>intersect by \",\"", -3.7376696182833684),
                                    ("at <time-of-day>absorption of , after named day",
                                     -3.7376696182833684),
                                    ("intersectintersect", -3.7376696182833684),
                                    ("<named-month> <day-of-month> (non ordinal)year",
                                     -3.332204510175204)],
                               n = 29},
                   koData =
                     ClassData{prior = -1.916922612182061, unseen = -3.6109179126442243,
                               likelihoods =
                                 HashMap.fromList
                                   [("named-daynamed-month", -1.791759469228055),
                                    ("daymonth", -1.791759469228055)],
                               n = 5}}),
       ("hh:mm",
        Classifier{okData =
                     ClassData{prior = -2.197890671877523e-2,
                               unseen = -3.8501476017100584,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 45},
                   koData =
                     ClassData{prior = -3.828641396489095, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("quarter after|past <integer> (hour-of-day)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("named-day",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.248495242049359,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 68},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("second (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("ordinals (first..twentieth,thirtieth,...)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.044522437723423,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 19},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time-of-day> sharp",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.4849066497880004,
                               likelihoods =
                                 HashMap.fromList
                                   [("at <time-of-day>", -1.2992829841302609),
                                    ("time-of-day (latent)", -1.2992829841302609),
                                    ("hour", -0.7884573603642702)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("intersect by \"of\", \"from\", \"'s\"",
        Classifier{okData =
                     ClassData{prior = -0.8649974374866046,
                               unseen = -3.1354942159291497,
                               likelihoods =
                                 HashMap.fromList
                                   [("named-daynamed-month", -1.4816045409242156),
                                    ("daymonth", -1.1451323043030026),
                                    ("named-daylast <cycle>", -2.3978952727983707),
                                    ("named-daynext <cycle>", -2.3978952727983707),
                                    ("named-dayintersect", -1.9924301646902063),
                                    ("dayweek", -1.9924301646902063)],
                               n = 8},
                   koData =
                     ClassData{prior = -0.5465437063680699, unseen = -3.367295829986474,
                               likelihoods =
                                 HashMap.fromList
                                   [("named-daynamed-month", -1.3862943611198906),
                                    ("daymonth", -0.8472978603872037),
                                    ("named-dayintersect", -1.540445040947149)],
                               n = 11}}),
       ("<duration> ago",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.4965075614664802,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.6739764335716716), ("day", -1.8562979903656263),
                                    ("year", -2.367123614131617),
                                    ("<integer> <unit-of-duration>", -0.9007865453381898),
                                    ("a <unit-of-duration>", -2.772588722239781),
                                    ("month", -2.367123614131617)],
                               n = 13},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("last <time>",
        Classifier{okData =
                     ClassData{prior = -2.6149597780361984, unseen = -2.70805020110221,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -1.540445040947149), ("named-day", -1.540445040947149),
                                    ("hour", -1.9459101490553135),
                                    ("week-end", -1.9459101490553135)],
                               n = 3},
                   koData =
                     ClassData{prior = -7.598590697792199e-2,
                               unseen = -4.442651256490317,
                               likelihoods =
                                 HashMap.fromList
                                   [("year (latent)", -1.540445040947149),
                                    ("day", -2.8213788864092133),
                                    ("time-of-day (latent)", -1.540445040947149),
                                    ("year", -1.540445040947149), ("named-day", -3.332204510175204),
                                    ("intersect by \"of\", \"from\", \"'s\"", -3.332204510175204),
                                    ("hour", -1.540445040947149)],
                               n = 38}}),
       ("<day-of-month> (ordinal)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..twentieth,thirtieth,...)",
                                     -0.916290731874155),
                                    ("ordinal (digits)", -0.5108256237659907)],
                               n = 8},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("the day after tomorrow",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("noon",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("until <time-of-day>",
        Classifier{okData =
                     ClassData{prior = -0.2876820724517809, unseen = -2.890371757896165,
                               likelihoods =
                                 HashMap.fromList
                                   [("at <time-of-day>", -0.8873031950009028),
                                    ("hour", -0.8873031950009028)],
                               n = 6},
                   koData =
                     ClassData{prior = -1.3862943611198906,
                               unseen = -2.3025850929940455,
                               likelihoods =
                                 HashMap.fromList
                                   [("intersect", -1.5040773967762742),
                                    ("hh:mm", -1.5040773967762742),
                                    ("minute", -1.0986122886681098)],
                               n = 2}}),
       ("<integer> and an half hours",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.6931471805599453),
                                    ("integer (0..19)", -0.6931471805599453)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("after <duration>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -0.6931471805599453),
                                    ("<integer> <unit-of-duration>", -0.6931471805599453)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("evening",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("decimal number",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("next <time>",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("named-month", -1.791759469228055),
                                    ("day", -1.0986122886681098),
                                    ("named-day", -1.0986122886681098),
                                    ("month", -1.791759469228055)],
                               n = 4},
                   koData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("named-month", -1.791759469228055),
                                    ("day", -1.0986122886681098),
                                    ("named-day", -1.0986122886681098),
                                    ("month", -1.791759469228055)],
                               n = 4}}),
       ("last <cycle>",
        Classifier{okData =
                     ClassData{prior = -0.587786664902119, unseen = -2.9444389791664407,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.5040773967762742),
                                    ("month (grain)", -2.1972245773362196),
                                    ("year (grain)", -2.1972245773362196),
                                    ("week (grain)", -1.5040773967762742),
                                    ("year", -2.1972245773362196), ("month", -2.1972245773362196)],
                               n = 5},
                   koData =
                     ClassData{prior = -0.8109302162163288, unseen = -2.833213344056216,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.6739764335716716),
                                    ("week (grain)", -1.6739764335716716),
                                    ("day", -1.6739764335716716),
                                    ("day (grain)", -1.6739764335716716)],
                               n = 4}}),
       ("christmas",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("new year's day",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("next n <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.912023005428146,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.793208009442517),
                                    ("integer (0..19)year (grain)", -3.1986731175506815),
                                    ("integer (numeric)day (grain)", -3.1986731175506815),
                                    ("integer (0..19)hour (grain)", -3.1986731175506815),
                                    ("second", -2.793208009442517),
                                    ("integer (numeric)second (grain)", -3.1986731175506815),
                                    ("integer (numeric)year (grain)", -3.1986731175506815),
                                    ("day", -2.793208009442517), ("year", -2.793208009442517),
                                    ("integer (numeric)week (grain)", -3.1986731175506815),
                                    ("integer (0..19)month (grain)", -3.1986731175506815),
                                    ("integer (0..19)second (grain)", -3.1986731175506815),
                                    ("hour", -2.793208009442517), ("month", -2.793208009442517),
                                    ("integer (numeric)minute (grain)", -3.1986731175506815),
                                    ("integer (0..19)minute (grain)", -3.1986731175506815),
                                    ("integer (numeric)month (grain)", -3.1986731175506815),
                                    ("minute", -2.793208009442517),
                                    ("integer (numeric)hour (grain)", -3.1986731175506815),
                                    ("integer (0..19)day (grain)", -3.1986731175506815),
                                    ("integer (0..19)week (grain)", -3.1986731175506815)],
                               n = 14},
                   koData =
                     ClassData{prior = -infinity, unseen = -3.0910424533583156,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("in <duration>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.3694478524670215,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -3.258096538021482),
                                    ("<integer> more <unit-of-duration>", -3.258096538021482),
                                    ("number.number hours", -3.6635616461296463),
                                    ("second", -2.9704144655697013), ("day", -2.5649493574615367),
                                    ("half an hour", -3.6635616461296463),
                                    ("<integer> <unit-of-duration>", -1.3121863889661687),
                                    ("a <unit-of-duration>", -2.5649493574615367),
                                    ("<integer> and an half hours", -3.258096538021482),
                                    ("hour", -2.4107986776342782), ("minute", -1.466337068793427),
                                    ("about <duration>", -3.258096538021482)],
                               n = 33},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.5649493574615367,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<datetime> - <datetime> (interval)",
        Classifier{okData =
                     ClassData{prior = -0.8362480242006186,
                               unseen = -3.6888794541139363,
                               likelihoods =
                                 HashMap.fromList
                                   [("minuteminute", -1.466337068793427),
                                    ("hh:mmhh:mm", -1.466337068793427),
                                    ("dayday", -1.8718021769015913),
                                    ("<day-of-month> (non ordinal) <named-month><day-of-month> (non ordinal) <named-month>",
                                     -1.8718021769015913)],
                               n = 13},
                   koData =
                     ClassData{prior = -0.5679840376059393, unseen = -3.871201010907891,
                               likelihoods =
                                 HashMap.fromList
                                   [("monthday", -2.0583881324820035),
                                    ("minuteminute", -1.9042374526547454),
                                    ("hh:mmhh:mm", -3.1570004211501135),
                                    ("dayyear", -2.751535313041949),
                                    ("year<hour-of-day> <integer> (as relative minutes)",
                                     -2.751535313041949),
                                    ("hh:mmintersect", -2.0583881324820035),
                                    ("dd/mmyear", -2.751535313041949),
                                    ("named-month<day-of-month> (non ordinal) <named-month>",
                                     -2.0583881324820035),
                                    ("<hour-of-day> <integer> (as relative minutes)year",
                                     -2.751535313041949),
                                    ("minuteyear", -2.751535313041949),
                                    ("yearminute", -2.751535313041949)],
                               n = 17}}),
       ("<time-of-day> - <time-of-day> (interval)",
        Classifier{okData =
                     ClassData{prior = -0.8109302162163288, unseen = -3.044522437723423,
                               likelihoods =
                                 HashMap.fromList
                                   [("minuteminute", -0.7985076962177716),
                                    ("hh:mmhh:mm", -0.7985076962177716)],
                               n = 8},
                   koData =
                     ClassData{prior = -0.587786664902119, unseen = -3.2188758248682006,
                               likelihoods =
                                 HashMap.fromList
                                   [("hh:mmtime-of-day (latent)", -0.8754687373538999),
                                    ("minuteminute", -2.4849066497880004),
                                    ("hh:mmhh:mm", -2.4849066497880004),
                                    ("minutehour", -0.8754687373538999)],
                               n = 10}}),
       ("last n <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.007333185232471,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.6026896854443837),
                                    ("integer (0..19)year (grain)", -3.295836866004329),
                                    ("integer (numeric)day (grain)", -2.890371757896165),
                                    ("second", -2.890371757896165),
                                    ("integer (numeric)second (grain)", -3.295836866004329),
                                    ("integer (numeric)year (grain)", -2.890371757896165),
                                    ("day", -2.6026896854443837), ("year", -2.6026896854443837),
                                    ("integer (numeric)week (grain)", -3.295836866004329),
                                    ("integer (0..19)month (grain)", -2.890371757896165),
                                    ("integer (0..19)second (grain)", -3.295836866004329),
                                    ("hour", -3.295836866004329), ("month", -2.6026896854443837),
                                    ("integer (numeric)minute (grain)", -3.295836866004329),
                                    ("integer (0..19)minute (grain)", -3.295836866004329),
                                    ("integer (numeric)month (grain)", -3.295836866004329),
                                    ("minute", -2.890371757896165),
                                    ("integer (numeric)hour (grain)", -3.295836866004329),
                                    ("integer (0..19)day (grain)", -3.295836866004329),
                                    ("integer (0..19)week (grain)", -2.890371757896165)],
                               n = 17},
                   koData =
                     ClassData{prior = -infinity, unseen = -3.044522437723423,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<named-month> <day-of-month> (non ordinal)",
        Classifier{okData =
                     ClassData{prior = -0.4418327522790392, unseen = -3.044522437723423,
                               likelihoods =
                                 HashMap.fromList
                                   [("named-monthinteger (numeric)", -0.6931471805599453),
                                    ("month", -0.6931471805599453)],
                               n = 9},
                   koData =
                     ClassData{prior = -1.0296194171811581,
                               unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("named-monthinteger (numeric)", -0.6931471805599453),
                                    ("month", -0.6931471805599453)],
                               n = 5}}),
       ("<day-of-month> (non ordinal) <named-month>",
        Classifier{okData =
                     ClassData{prior = -0.1466034741918754, unseen = -3.713572066704308,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)named-month", -0.6931471805599453),
                                    ("month", -0.6931471805599453)],
                               n = 19},
                   koData =
                     ClassData{prior = -1.9924301646902063,
                               unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)named-month", -0.6931471805599453),
                                    ("month", -0.6931471805599453)],
                               n = 3}}),
       ("this|next <day-of-week>",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -0.6931471805599453),
                                    ("named-day", -0.6931471805599453)],
                               n = 3},
                   koData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -0.6931471805599453),
                                    ("named-day", -0.6931471805599453)],
                               n = 3}}),
       ("ordinal (digits)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.4849066497880004,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 10},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("quarter (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("last <cycle> of <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.1354942159291497,
                               likelihoods =
                                 HashMap.fromList
                                   [("daymonth", -1.4816045409242156),
                                    ("week (grain)named-month", -1.9924301646902063),
                                    ("day (grain)intersect", -1.9924301646902063),
                                    ("weekmonth", -1.4816045409242156),
                                    ("day (grain)named-month", -1.9924301646902063),
                                    ("week (grain)intersect", -1.9924301646902063)],
                               n = 8},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<day-of-month>(ordinal) <named-month> year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3025850929940455,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..twentieth,thirtieth,...)named-month",
                                     -1.0986122886681098),
                                    ("ordinal (digits)named-month", -1.5040773967762742),
                                    ("month", -0.8109302162163288)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("morning",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("week-end",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("after <time-of-day>",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453, unseen = -3.332204510175204,
                               likelihoods =
                                 HashMap.fromList
                                   [("at <time-of-day>", -1.6863989535702288),
                                    ("intersect", -2.1972245773362196),
                                    ("tomorrow", -2.1972245773362196), ("day", -2.1972245773362196),
                                    ("hour", -1.349926716949016)],
                               n = 8},
                   koData =
                     ClassData{prior = -0.6931471805599453, unseen = -3.332204510175204,
                               likelihoods =
                                 HashMap.fromList
                                   [("lunch", -2.6026896854443837),
                                    ("year (latent)", -1.9095425048844386),
                                    ("time-of-day (latent)", -1.9095425048844386),
                                    ("year", -1.9095425048844386), ("hh:mm", -2.6026896854443837),
                                    ("hour", -1.6863989535702288), ("minute", -2.6026896854443837)],
                               n = 8}}),
       ("day (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.044522437723423,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 19},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<month> dd-dd (interval)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("named-month", -0.6931471805599453),
                                    ("month", -0.6931471805599453)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("about <duration>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("half an hour", -0.6931471805599453),
                                    ("minute", -0.6931471805599453)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<hour-of-day> <integer> (as relative minutes)",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -3.044522437723423,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)integer (numeric)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 9}}),
       ("this <time>",
        Classifier{okData =
                     ClassData{prior = -1.276293465905562, unseen = -3.6109179126442243,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.890371757896165),
                                    ("intersect", -2.4849066497880004),
                                    ("season", -1.9740810260220096),
                                    ("next <cycle>", -2.890371757896165),
                                    ("named-month", -2.4849066497880004),
                                    ("day", -1.9740810260220096), ("hour", -2.1972245773362196),
                                    ("month", -1.9740810260220096),
                                    ("week-end", -2.1972245773362196)],
                               n = 12},
                   koData =
                     ClassData{prior = -0.3272129112084162, unseen = -4.31748811353631,
                               likelihoods =
                                 HashMap.fromList
                                   [("intersect", -1.8191584434161694),
                                    ("named-month", -1.4708517491479536),
                                    ("time-of-day (latent)", -3.20545280453606),
                                    ("noon", -3.6109179126442243), ("hour", -2.6946271807700692),
                                    ("month", -0.9718605830289657),
                                    ("morning", -3.6109179126442243)],
                               n = 31}}),
       ("within <duration>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -0.6931471805599453),
                                    ("<integer> <unit-of-duration>", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}})]